notifications:
  email: false
matrix:
  include:
    - stage: Image Asset Validation
      language: bash
      before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y imagemagick
      script:
        - tests/image_translucency.sh
        - tests/image_dimensions.sh
    - stage: JSON Asset Validation
      language: node_js
      before_install:
        - npm install jsonlint
      script:
        - tests/json_validate.sh
    - stage: Translation Check
      language: python
      script:
        - tests/localize_check.py
    - stage: Recompilation
      language: java
      script:
        - tests/recompile.sh
cache:
  directories:
    - "node_modules"
git:
  depth: 1
