package net.minecraft.init;

import com.elementfx.tvp.ad.item.ItemPipe;

import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.Item;
import net.minecraft.item.ItemArmor;
import net.minecraft.item.ItemArmorStand;
import net.minecraft.item.ItemBow;
import net.minecraft.item.ItemEmptyMap;
import net.minecraft.item.ItemEnchantedBook;
import net.minecraft.item.ItemFishingRod;
import net.minecraft.item.ItemMap;
import net.minecraft.item.ItemPotion;
import net.minecraft.item.ItemSeeds;
import net.minecraft.item.ItemShears;
import net.minecraft.util.ResourceLocation;

public class Items
{
    public static final Item IRON_SHOVEL;
    public static final Item IRON_PICKAXE;
    public static final Item IRON_AXE;
    public static final Item FLINT_AND_STEEL;
    public static final Item APPLE;
    public static final ItemBow BOW;
    public static final Item ARROW;
    public static final Item SPECTRAL_ARROW;
    public static final Item TIPPED_ARROW;
    public static final Item COAL;
    public static final Item DIAMOND;
    public static final Item IRON_INGOT;
    public static final Item GOLD_INGOT;
    public static final Item IRON_SWORD;
    public static final Item WOODEN_SWORD;
    public static final Item WOODEN_SHOVEL;
    public static final Item WOODEN_PICKAXE;
    public static final Item WOODEN_AXE;
    public static final Item STONE_SWORD;
    public static final Item STONE_SHOVEL;
    public static final Item STONE_PICKAXE;
    public static final Item STONE_AXE;
    public static final Item DIAMOND_SWORD;
    public static final Item DIAMOND_SHOVEL;
    public static final Item DIAMOND_PICKAXE;
    public static final Item DIAMOND_AXE;
    public static final Item STICK;
    public static final Item BOWL;
    public static final Item MUSHROOM_STEW;
    public static final Item GOLDEN_SWORD;
    public static final Item GOLDEN_SHOVEL;
    public static final Item GOLDEN_PICKAXE;
    public static final Item GOLDEN_AXE;
    public static final Item STRING;
    public static final Item FEATHER;
    public static final Item GUNPOWDER;
    public static final Item WOODEN_HOE;
    public static final Item STONE_HOE;
    public static final Item IRON_HOE;
    public static final Item DIAMOND_HOE;
    public static final Item GOLDEN_HOE;
    public static final Item WHEAT_SEEDS;
    public static final Item WHEAT;
    public static final Item BREAD;
    public static final ItemArmor LEATHER_HELMET;
    public static final ItemArmor LEATHER_CHESTPLATE;
    public static final ItemArmor LEATHER_LEGGINGS;
    public static final ItemArmor LEATHER_BOOTS;
    public static final ItemArmor CHAINMAIL_HELMET;
    public static final ItemArmor CHAINMAIL_CHESTPLATE;
    public static final ItemArmor CHAINMAIL_LEGGINGS;
    public static final ItemArmor CHAINMAIL_BOOTS;
    public static final ItemArmor IRON_HELMET;
    public static final ItemArmor IRON_CHESTPLATE;
    public static final ItemArmor IRON_LEGGINGS;
    public static final ItemArmor IRON_BOOTS;
    public static final ItemArmor DIAMOND_HELMET;
    public static final ItemArmor DIAMOND_CHESTPLATE;
    public static final ItemArmor DIAMOND_LEGGINGS;
    public static final ItemArmor DIAMOND_BOOTS;
    public static final ItemArmor GOLDEN_HELMET;
    public static final ItemArmor GOLDEN_CHESTPLATE;
    public static final ItemArmor GOLDEN_LEGGINGS;
    public static final ItemArmor GOLDEN_BOOTS;
    public static final Item FLINT;
    public static final Item PORKCHOP;
    public static final Item COOKED_PORKCHOP;
    public static final Item PAINTING;
    public static final Item GOLDEN_APPLE;
    public static final Item SIGN;
    public static final Item OAK_DOOR;
    public static final Item SPRUCE_DOOR;
    public static final Item BIRCH_DOOR;
    public static final Item JUNGLE_DOOR;
    public static final Item ACACIA_DOOR;
    public static final Item DARK_OAK_DOOR;
    public static final Item BUCKET;
    public static final Item WATER_BUCKET;
    public static final Item LAVA_BUCKET;
    public static final Item MINECART;
    public static final Item SADDLE;
    public static final Item IRON_DOOR;
    public static final Item REDSTONE;
    public static final Item SNOWBALL;
    public static final Item BOAT;
    public static final Item SPRUCE_BOAT;
    public static final Item BIRCH_BOAT;
    public static final Item JUNGLE_BOAT;
    public static final Item ACACIA_BOAT;
    public static final Item DARK_OAK_BOAT;
    public static final Item LEATHER;
    public static final Item MILK_BUCKET;
    public static final Item BRICK;
    public static final Item CLAY_BALL;
    public static final Item REEDS;
    public static final Item PAPER;
    public static final Item BOOK;
    public static final Item SLIME_BALL;
    public static final Item CHEST_MINECART;
    public static final Item FURNACE_MINECART;
    public static final Item EGG;
    public static final Item COMPASS;
    public static final ItemFishingRod FISHING_ROD;
    public static final Item CLOCK;
    public static final Item GLOWSTONE_DUST;
    public static final Item FISH;
    public static final Item COOKED_FISH;
    public static final Item DYE;
    public static final Item BONE;
    public static final Item SUGAR;
    public static final Item CAKE;
    public static final Item BED;
    public static final Item REPEATER;
    public static final Item COOKIE;
    public static final ItemMap FILLED_MAP;
    public static final ItemShears SHEARS;
    public static final Item MELON;
    public static final Item PUMPKIN_SEEDS;
    public static final Item MELON_SEEDS;
    public static final Item BEEF;
    public static final Item COOKED_BEEF;
    public static final Item CHICKEN;
    public static final Item COOKED_CHICKEN;
    public static final Item MUTTON;
    public static final Item COOKED_MUTTON;
    public static final Item RABBIT;
    public static final Item COOKED_RABBIT;
    public static final Item RABBIT_STEW;
    public static final Item RABBIT_FOOT;
    public static final Item RABBIT_HIDE;
    public static final Item ROTTEN_FLESH;
    public static final Item ENDER_PEARL;
    public static final Item BLAZE_ROD;
    public static final Item GHAST_TEAR;
    public static final Item GOLD_NUGGET;
    public static final Item NETHER_WART;
    public static final ItemPotion POTIONITEM;
    public static final ItemPotion SPLASH_POTION;
    public static final ItemPotion LINGERING_POTION;
    public static final Item GLASS_BOTTLE;
    public static final Item DRAGON_BREATH;
    public static final Item SPIDER_EYE;
    public static final Item FERMENTED_SPIDER_EYE;
    public static final Item BLAZE_POWDER;
    public static final Item MAGMA_CREAM;
    public static final Item BREWING_STAND;
    public static final Item CAULDRON;
    public static final Item ENDER_EYE;
    public static final Item SPECKLED_MELON;
    public static final Item SPAWN_EGG;
    public static final Item EXPERIENCE_BOTTLE;
    public static final Item FIRE_CHARGE;
    public static final Item WRITABLE_BOOK;
    public static final Item WRITTEN_BOOK;
    public static final Item EMERALD;
    public static final Item ITEM_FRAME;
    public static final Item FLOWER_POT;
    public static final Item CARROT;
    public static final Item POTATO;
    public static final Item BAKED_POTATO;
    public static final Item POISONOUS_POTATO;
    public static final ItemEmptyMap MAP;
    public static final Item GOLDEN_CARROT;
    public static final Item SKULL;
    public static final Item CARROT_ON_A_STICK;
    public static final Item NETHER_STAR;
    public static final Item PUMPKIN_PIE;
    public static final Item FIREWORKS;
    public static final Item FIREWORK_CHARGE;
    public static final ItemEnchantedBook ENCHANTED_BOOK;
    public static final Item COMPARATOR;
    public static final Item NETHERBRICK;
    public static final Item QUARTZ;
    public static final Item TNT_MINECART;
    public static final Item HOPPER_MINECART;
    public static final ItemArmorStand ARMOR_STAND;
    public static final Item IRON_HORSE_ARMOR;
    public static final Item GOLDEN_HORSE_ARMOR;
    public static final Item DIAMOND_HORSE_ARMOR;
    public static final Item LEAD;
    public static final Item NAME_TAG;
    public static final Item COMMAND_BLOCK_MINECART;
    public static final Item RECORD_13;
    public static final Item RECORD_CAT;
    public static final Item RECORD_BLOCKS;
    public static final Item RECORD_CHIRP;
    public static final Item RECORD_FAR;
    public static final Item RECORD_MALL;
    public static final Item RECORD_MELLOHI;
    public static final Item RECORD_STAL;
    public static final Item RECORD_STRAD;
    public static final Item RECORD_WARD;
    public static final Item RECORD_11;
    public static final Item RECORD_WAIT;
    public static final Item PRISMARINE_SHARD;
    public static final Item PRISMARINE_CRYSTALS;
    public static final Item BANNER;
    public static final Item END_CRYSTAL;
    public static final Item SHIELD;
    public static final Item ELYTRA;
    public static final Item CHORUS_FRUIT;
    public static final Item CHORUS_FRUIT_POPPED;
    public static final Item BEETROOT_SEEDS;
    public static final Item BEETROOT;
    public static final Item BEETROOT_SOUP;
    // Begin Awaken Dreams code
    public static final Item LEMBAS;
    public static final Item MITHRIL_INGOT;
    public static final Item BRONZE_INGOT;
    public static final ItemPipe PIPE;
    public static final Item TOBACCO;
    public static final Item JADE;
    public static final Item AMBER;
    public static final Item CRYSTAL;
    public static final Item AMETHYST;
    public static final Item ONYX;
    public static final Item MOONSTONE;
    public static final Item TANZANITE;
    public static final Item URUK_SWORD;
    public static final Item TOMATO;
    public static final Item BLUE_FEATHER;
    public static final Item SPIDER_POISON;
    public static final Item HERUGRIM;
    public static final Item NUTS;
    public static final Item CORN_COB;
    public static final Item STAFF_BASE;
    public static final Item KNIFE;
    public static final Item BERRIES;
    public static final Item BEAR_CLAW;
    public static final Item BEAST_SKIN;
    public static final Item DEAD_ROOT;
    public static final Item EAGLE_FEATHER;
    public static final Item GOBLIN_EYE;
    public static final Item HELEGROG_DEAMON_HEART;
    public static final Item ORC_BLOOD;
    public static final Item OWL_FEATHER;
    public static final Item SCORPION_TAIL;
    public static final Item SHARK_TOOTH;
    public static final Item TROLL_SKIN;
    public static final Item WARG_FANG;
    public static final Item BLUE_BED;
    public static final Item BROWN_BED;
    public static final Item BREE_DOOR;
    public static final Item RUCKSACK;
    public static final Item CRAM;
    public static final Item CABBAGE;
    public static final Item COCONUT;
    public static final Item RAW_DEER_MEAT;
    public static final Item COOKED_DEER_MEAT;
    public static final Item MUFFIN;
    public static final Item STRAWBERRY;
    public static final Item STRAWBERRY_MUFFIN;
    public static final Item ORANGE;
    public static final Item ORANGE_MUFFIN;
    public static final Item PEAR;
    public static final Item RAW_MEAT;
    public static final Item COOKED_MEAT;
    public static final Item ROHAN_HELMET_1;
    public static final Item ROHAN_HELMET_2;
    public static final Item ROHAN_HELMET_3;
    public static final Item ROHAN_HELMET_4;
    public static final Item ROHAN_HELMET_5;
    public static final Item ROHAN_HELMET_6;
    public static final Item ROHAN_CHESTPLATE;
    public static final Item TELESCOPE;
    public static final Item HUMAN_DAGGER;
    public static final Item HOBBIT_DAGGER;
    public static final Item ELF_DAGGER;
    public static final Item GONDORIAN_SWORD;
    public static final Item SOUTHERN_STAR;
    public static final Item SOUTHLINCH;
    public static final Item OLD_TOBY;
    public static final Item STONE_OF_DARKNESS;
    public static final Item STONE_OF_EARTH;
    public static final Item STONE_OF_FIRE;
    public static final Item STONE_OF_GREED;
    public static final Item STONE_OF_HOPE;
    public static final Item STONE_OF_NATURE;
    public static final Item STONE_OF_SUNLIGHT;
    public static final Item STONE_OF_SEA;
    public static final Item STONE_OF_SKY;
    public static final Item STONE_OF_WEALTH;
    public static final Item STONE_OF_WIND;
    public static final Item HAMMER;
    public static final Item GOLD_RING;
    public static final Item ONYX_GOLD_RING;
    public static final Item TANZANITE_GOLD_RING;
    public static final Item JADE_GOLD_RING;
    public static final Item MOONSTONE_GOLD_RING;
    public static final Item AMETHYST_GOLD_RING;
    public static final Item RUBY_GOLD_RING;
    public static final Item QUARTZ_GOLD_RING;
    public static final Item AMBER_GOLD_RING;
    public static final Item SILVER_RING;
    public static final Item ONYX_SILVER_RING;
    public static final Item TANZANITE_SILVER_RING;
    public static final Item JADE_SILVER_RING;
    public static final Item MOONSTONE_SILVER_RING;
    public static final Item AMETHYST_SILVER_RING;
    public static final Item RUBY_SILVER_RING;
    public static final Item QUARTZ_SILVER_RING;
    public static final Item AMBER_SILVER_RING;
    public static final Item BRONZE_RING;
    public static final Item ONYX_BRONZE_RING;
    public static final Item TANZANITE_BRONZE_RING;
    public static final Item JADE_BRONZE_RING;
    public static final Item MOONSTONE_BRONZE_RING;
    public static final Item AMETHYST_BRONZE_RING;
    public static final Item RUBY_BRONZE_RING;
    public static final Item QUARTZ_BRONZE_RING;
    public static final Item AMBER_BRONZE_RING;
    public static final Item MITHRIL_RING;
    public static final Item ONYX_MITHRIL_RING;
    public static final Item TANZANITE_MITHRIL_RING;
    public static final Item JADE_MITHRIL_RING;
    public static final Item MOONSTONE_MITHRIL_RING;
    public static final Item AMETHYST_MITHRIL_RING;
    public static final Item RUBY_MITHRIL_RING;
    public static final Item QUARTZ_MITHRIL_RING;
    public static final Item AMBER_MITHRIL_RING;
    public static final Item SALT;
    public static final Item NOLDOR_CHESTPLATE;
    public static final Item SILVER_INGOT;
    public static final Item DWARF_DOOR;
    public static final Item BOROMIRS_SWORD;
    public static final Item ORC_SWORD_1;
    public static final Item ORC_SWORD_2;
    public static final Item GOBLIN_SWORD;
    public static final Item HOBBIT_AXE;
    public static final Item SHARKUS_SHORTSWORD;
    public static final Item BATTLE_PICKAXE;
    public static final Item SHIRRIFF_CLUB;
    public static final Item PIKE_CLUB;
    public static final Item HOBBIT_SWORD;
    public static final Item HOBBIT_HAMMER;
    public static final Item BOAR_HORNS;
    public static final Item GOLD_RING_OF_DARKNESS;
    public static final Item GOLD_RING_OF_EARTH;
    public static final Item GOLD_RING_OF_FIRE;
    public static final Item GOLD_RING_OF_GREED;
    public static final Item GOLD_RING_OF_HOPE;
    public static final Item GOLD_RING_OF_NATURE;
    public static final Item GOLD_RING_OF_SEA;
    public static final Item GOLD_RING_OF_SKY;
    public static final Item GOLD_RING_OF_SUNLIGHT;
    public static final Item GOLD_RING_OF_WEALTH;
    public static final Item GOLD_RING_OF_WIND;
    public static final Item SILVER_RING_OF_DARKNESS;
    public static final Item SILVER_RING_OF_EARTH;
    public static final Item SILVER_RING_OF_FIRE;
    public static final Item SILVER_RING_OF_GREED;
    public static final Item SILVER_RING_OF_HOPE;
    public static final Item SILVER_RING_OF_NATURE;
    public static final Item SILVER_RING_OF_SEA;
    public static final Item SILVER_RING_OF_SKY;
    public static final Item SILVER_RING_OF_SUNLIGHT;
    public static final Item SILVER_RING_OF_WEALTH;
    public static final Item SILVER_RING_OF_WIND;
    public static final Item BRONZE_RING_OF_DARKNESS;
    public static final Item BRONZE_RING_OF_EARTH;
    public static final Item BRONZE_RING_OF_FIRE;
    public static final Item BRONZE_RING_OF_GREED;
    public static final Item BRONZE_RING_OF_HOPE;
    public static final Item BRONZE_RING_OF_NATURE;
    public static final Item BRONZE_RING_OF_SEA;
    public static final Item BRONZE_RING_OF_SKY;
    public static final Item BRONZE_RING_OF_SUNLIGHT;
    public static final Item BRONZE_RING_OF_WEALTH;
    public static final Item BRONZE_RING_OF_WIND;
    public static final Item MITHRIL_RING_OF_DARKNESS;
    public static final Item MITHRIL_RING_OF_EARTH;
    public static final Item MITHRIL_RING_OF_FIRE;
    public static final Item MITHRIL_RING_OF_GREED;
    public static final Item MITHRIL_RING_OF_HOPE;
    public static final Item MITHRIL_RING_OF_NATURE;
    public static final Item MITHRIL_RING_OF_SEA;
    public static final Item MITHRIL_RING_OF_SKY;
    public static final Item MITHRIL_RING_OF_SUNLIGHT;
    public static final Item MITHRIL_RING_OF_WEALTH;
    public static final Item MITHRIL_RING_OF_WIND;
    public static final Item ANDURIL;
    public static final Item MORGUL_SWORD;
    public static final Item ELVEN_LONG_SWORD;
    public static final Item BERSERKER_SWORD;
    public static final Item TWO_HANDED_SWORD;
    public static final Item THROWING_STONE;
    public static final Item ROHIRRIM_AXE;
    public static final Item ELVEN_DOOR;
    public static final Item HUMAN_DOOR;
    public static final Item GREEN_BED;
    public static final Item AICANAR;
    public static final Item BALINS_SWORD;
    public static final Item BIFURS_SPEAR;
    public static final Item BOMBURS_SPOON;
    public static final Item DORIS_SWORD;
    public static final Item DWALINS_AXE;
    public static final Item FILIS_KNIFE;
    public static final Item FILIS_SWORD;
    public static final Item KILIS_SWORD;
    public static final Item NORIS_CLUB;
    public static final Item OINS_STAFF;
    public static final Item ORCRIST;
    public static final Item SWORD_OF_WESTERNESSE;
    public static final Item THORINS_SWORD;
    public static final Item THRAINS_WAR_HAMMER;
    public static final Item THRORS_WAR_HAMMER;
    public static final Item ARAGORNS_ELF_KNIFE;
    public static final Item EOWYNS_SWORD;
    public static final Item GANDALF_THE_GREYS_STAFF;
    public static final Item GANDALF_THE_WHITES_STAFF;
    public static final Item GIMLIS_TWO_HEADED_AXE;
    public static final Item GIMLIS_LONGAXE;
    public static final Item GLAMDRING;
    public static final Item GLOINS_AXE;
    public static final Item GLORFINDELS_SWORD;
    public static final Item GUTHWINE;
    public static final Item HADHAFANG;
    public static final Item LEGOLAS_SWORD;
    public static final Item RADAGASTS_STAFF;
    public static final Item LURTZ_SWORD;
    public static final Item SAURONS_MACE;
    public static final Item SARUMANS_STAFF;
    public static final Item YAZNEGS_AXE;
    public static final Item DWARVEN_LORD_KNIFE;
    public static final Item GONDORIAN_NOBLE_SWORD;
    public static final Item MACE_OF_GLORY;
    public static final Item GOLDEN_WAR_HAMMER_OF_EREBOR;
    public static final Item GONDORIAN_SPEAR;
    public static final Item ROHIRRIM_SPEAR;
    public static final Item BULL_HEAD_MACE;
    public static final Item CORSAIR_EKET;
    public static final Item DOL_GULDUR_SPIKED_MACE;
    public static final Item FELL_WARGRIDER_SWORD;
    public static final Item HARADRIM_SNAKE_DAGGER;
    public static final Item NORTH_GOBLIN_MACE;
    public static final Item NORTH_GOBLIN_SWORD;
    public static final Item ORC_CAPTAIN_SWORD;
    public static final Item ORC_DAGGER;
    public static final Item ORC_HALBARD;
    public static final Item URUK_SIEGE_TROOPER_DAGGER;
    public static final Item IRON_MACE;
    public static final Item ORC_SWORD_3;
    public static final Item MORANNON_DAGGER;
    public static final Item ORC_SPEAR;
    public static final Item CASTLE_DOOR;
    public static final Item DOL_GULDUR_PRISON_DOOR;
    public static final Item HILLMEN_DOOR;
    public static final Item MORDOR_DOOR;
    public static final Item PRISON_DOOR;
    public static final Item SINDAR_DOOR;
    public static final Item SOUTHLINCH_SEED;
    public static final Item GREEN_GRAPE_SEED;
    public static final Item GREEN_GRAPES;
    public static final Item PURPLE_GRAPE_SEED;
    public static final Item PURPLE_GRAPES;
    public static final Item PIPEWEED_SEED;
    public static final Item PEAS;
    public static final Item PEA_POD;
    public static final Item LEEK;
    public static final Item LEEK_SEED;
    public static final Item ONION_SEED;
    public static final Item ONION;
    public static final Item OLD_TOBY_SEED;
    public static final Item SOUTHERN_STAR_SEED;
    public static final Item STRAWBERRY_SEED;
    public static final Item ROHAN_BOOTS;
    public static final Item ROHAN_LEGGINGS;
    public static final Item RING;
    public static final Item ELVEN_STEEL_INGOT;
    // End Awaken Dreams code

    private static Item getRegisteredItem(String name)
    {
        Item item = (Item)Item.REGISTRY.getObject(new ResourceLocation(name));

        if (item == null)
        {
            throw new IllegalStateException("Invalid Item requested: " + name);
        }
        else
        {
            return item;
        }
    }

    static
    {
        if (!Bootstrap.isRegistered())
        {
            throw new RuntimeException("Accessed Items before Bootstrap!");
        }
        else
        {
            IRON_SHOVEL = getRegisteredItem("iron_shovel");
            IRON_PICKAXE = getRegisteredItem("iron_pickaxe");
            IRON_AXE = getRegisteredItem("iron_axe");
            FLINT_AND_STEEL = getRegisteredItem("flint_and_steel");
            APPLE = getRegisteredItem("apple");
            BOW = (ItemBow)getRegisteredItem("bow");
            ARROW = getRegisteredItem("arrow");
            SPECTRAL_ARROW = getRegisteredItem("spectral_arrow");
            TIPPED_ARROW = getRegisteredItem("tipped_arrow");
            COAL = getRegisteredItem("coal");
            DIAMOND = getRegisteredItem("diamond");
            IRON_INGOT = getRegisteredItem("iron_ingot");
            GOLD_INGOT = getRegisteredItem("gold_ingot");
            IRON_SWORD = getRegisteredItem("iron_sword");
            WOODEN_SWORD = getRegisteredItem("wooden_sword");
            WOODEN_SHOVEL = getRegisteredItem("wooden_shovel");
            WOODEN_PICKAXE = getRegisteredItem("wooden_pickaxe");
            WOODEN_AXE = getRegisteredItem("wooden_axe");
            STONE_SWORD = getRegisteredItem("stone_sword");
            STONE_SHOVEL = getRegisteredItem("stone_shovel");
            STONE_PICKAXE = getRegisteredItem("stone_pickaxe");
            STONE_AXE = getRegisteredItem("stone_axe");
            DIAMOND_SWORD = getRegisteredItem("diamond_sword");
            DIAMOND_SHOVEL = getRegisteredItem("diamond_shovel");
            DIAMOND_PICKAXE = getRegisteredItem("diamond_pickaxe");
            DIAMOND_AXE = getRegisteredItem("diamond_axe");
            STICK = getRegisteredItem("stick");
            BOWL = getRegisteredItem("bowl");
            MUSHROOM_STEW = getRegisteredItem("mushroom_stew");
            GOLDEN_SWORD = getRegisteredItem("golden_sword");
            GOLDEN_SHOVEL = getRegisteredItem("golden_shovel");
            GOLDEN_PICKAXE = getRegisteredItem("golden_pickaxe");
            GOLDEN_AXE = getRegisteredItem("golden_axe");
            STRING = getRegisteredItem("string");
            FEATHER = getRegisteredItem("feather");
            GUNPOWDER = getRegisteredItem("gunpowder");
            WOODEN_HOE = getRegisteredItem("wooden_hoe");
            STONE_HOE = getRegisteredItem("stone_hoe");
            IRON_HOE = getRegisteredItem("iron_hoe");
            DIAMOND_HOE = getRegisteredItem("diamond_hoe");
            GOLDEN_HOE = getRegisteredItem("golden_hoe");
            WHEAT_SEEDS = getRegisteredItem("wheat_seeds");
            WHEAT = getRegisteredItem("wheat");
            BREAD = getRegisteredItem("bread");
            LEATHER_HELMET = (ItemArmor)getRegisteredItem("leather_helmet");
            LEATHER_CHESTPLATE = (ItemArmor)getRegisteredItem("leather_chestplate");
            LEATHER_LEGGINGS = (ItemArmor)getRegisteredItem("leather_leggings");
            LEATHER_BOOTS = (ItemArmor)getRegisteredItem("leather_boots");
            CHAINMAIL_HELMET = (ItemArmor)getRegisteredItem("chainmail_helmet");
            CHAINMAIL_CHESTPLATE = (ItemArmor)getRegisteredItem("chainmail_chestplate");
            CHAINMAIL_LEGGINGS = (ItemArmor)getRegisteredItem("chainmail_leggings");
            CHAINMAIL_BOOTS = (ItemArmor)getRegisteredItem("chainmail_boots");
            IRON_HELMET = (ItemArmor)getRegisteredItem("iron_helmet");
            IRON_CHESTPLATE = (ItemArmor)getRegisteredItem("iron_chestplate");
            IRON_LEGGINGS = (ItemArmor)getRegisteredItem("iron_leggings");
            IRON_BOOTS = (ItemArmor)getRegisteredItem("iron_boots");
            DIAMOND_HELMET = (ItemArmor)getRegisteredItem("diamond_helmet");
            DIAMOND_CHESTPLATE = (ItemArmor)getRegisteredItem("diamond_chestplate");
            DIAMOND_LEGGINGS = (ItemArmor)getRegisteredItem("diamond_leggings");
            DIAMOND_BOOTS = (ItemArmor)getRegisteredItem("diamond_boots");
            GOLDEN_HELMET = (ItemArmor)getRegisteredItem("golden_helmet");
            GOLDEN_CHESTPLATE = (ItemArmor)getRegisteredItem("golden_chestplate");
            GOLDEN_LEGGINGS = (ItemArmor)getRegisteredItem("golden_leggings");
            GOLDEN_BOOTS = (ItemArmor)getRegisteredItem("golden_boots");
            FLINT = getRegisteredItem("flint");
            PORKCHOP = getRegisteredItem("porkchop");
            COOKED_PORKCHOP = getRegisteredItem("cooked_porkchop");
            PAINTING = getRegisteredItem("painting");
            GOLDEN_APPLE = getRegisteredItem("golden_apple");
            SIGN = getRegisteredItem("sign");
            OAK_DOOR = getRegisteredItem("wooden_door");
            SPRUCE_DOOR = getRegisteredItem("spruce_door");
            BIRCH_DOOR = getRegisteredItem("birch_door");
            JUNGLE_DOOR = getRegisteredItem("jungle_door");
            ACACIA_DOOR = getRegisteredItem("acacia_door");
            DARK_OAK_DOOR = getRegisteredItem("dark_oak_door");
            BUCKET = getRegisteredItem("bucket");
            WATER_BUCKET = getRegisteredItem("water_bucket");
            LAVA_BUCKET = getRegisteredItem("lava_bucket");
            MINECART = getRegisteredItem("minecart");
            SADDLE = getRegisteredItem("saddle");
            IRON_DOOR = getRegisteredItem("iron_door");
            REDSTONE = getRegisteredItem("redstone");
            SNOWBALL = getRegisteredItem("snowball");
            BOAT = getRegisteredItem("boat");
            SPRUCE_BOAT = getRegisteredItem("spruce_boat");
            BIRCH_BOAT = getRegisteredItem("birch_boat");
            JUNGLE_BOAT = getRegisteredItem("jungle_boat");
            ACACIA_BOAT = getRegisteredItem("acacia_boat");
            DARK_OAK_BOAT = getRegisteredItem("dark_oak_boat");
            LEATHER = getRegisteredItem("leather");
            MILK_BUCKET = getRegisteredItem("milk_bucket");
            BRICK = getRegisteredItem("brick");
            CLAY_BALL = getRegisteredItem("clay_ball");
            REEDS = getRegisteredItem("reeds");
            PAPER = getRegisteredItem("paper");
            BOOK = getRegisteredItem("book");
            SLIME_BALL = getRegisteredItem("slime_ball");
            CHEST_MINECART = getRegisteredItem("chest_minecart");
            FURNACE_MINECART = getRegisteredItem("furnace_minecart");
            EGG = getRegisteredItem("egg");
            COMPASS = getRegisteredItem("compass");
            FISHING_ROD = (ItemFishingRod)getRegisteredItem("fishing_rod");
            CLOCK = getRegisteredItem("clock");
            GLOWSTONE_DUST = getRegisteredItem("glowstone_dust");
            FISH = getRegisteredItem("fish");
            COOKED_FISH = getRegisteredItem("cooked_fish");
            DYE = getRegisteredItem("dye");
            BONE = getRegisteredItem("bone");
            SUGAR = getRegisteredItem("sugar");
            CAKE = getRegisteredItem("cake");
            BED = getRegisteredItem("bed");
            REPEATER = getRegisteredItem("repeater");
            COOKIE = getRegisteredItem("cookie");
            FILLED_MAP = (ItemMap)getRegisteredItem("filled_map");
            SHEARS = (ItemShears)getRegisteredItem("shears");
            MELON = getRegisteredItem("melon");
            PUMPKIN_SEEDS = getRegisteredItem("pumpkin_seeds");
            MELON_SEEDS = getRegisteredItem("melon_seeds");
            BEEF = getRegisteredItem("beef");
            COOKED_BEEF = getRegisteredItem("cooked_beef");
            CHICKEN = getRegisteredItem("chicken");
            COOKED_CHICKEN = getRegisteredItem("cooked_chicken");
            MUTTON = getRegisteredItem("mutton");
            COOKED_MUTTON = getRegisteredItem("cooked_mutton");
            RABBIT = getRegisteredItem("rabbit");
            COOKED_RABBIT = getRegisteredItem("cooked_rabbit");
            RABBIT_STEW = getRegisteredItem("rabbit_stew");
            RABBIT_FOOT = getRegisteredItem("rabbit_foot");
            RABBIT_HIDE = getRegisteredItem("rabbit_hide");
            ROTTEN_FLESH = getRegisteredItem("rotten_flesh");
            ENDER_PEARL = getRegisteredItem("ender_pearl");
            BLAZE_ROD = getRegisteredItem("blaze_rod");
            GHAST_TEAR = getRegisteredItem("ghast_tear");
            GOLD_NUGGET = getRegisteredItem("gold_nugget");
            NETHER_WART = getRegisteredItem("nether_wart");
            POTIONITEM = (ItemPotion)getRegisteredItem("potion");
            SPLASH_POTION = (ItemPotion)getRegisteredItem("splash_potion");
            LINGERING_POTION = (ItemPotion)getRegisteredItem("lingering_potion");
            GLASS_BOTTLE = getRegisteredItem("glass_bottle");
            DRAGON_BREATH = getRegisteredItem("dragon_breath");
            SPIDER_EYE = getRegisteredItem("spider_eye");
            FERMENTED_SPIDER_EYE = getRegisteredItem("fermented_spider_eye");
            BLAZE_POWDER = getRegisteredItem("blaze_powder");
            MAGMA_CREAM = getRegisteredItem("magma_cream");
            BREWING_STAND = getRegisteredItem("brewing_stand");
            CAULDRON = getRegisteredItem("cauldron");
            ENDER_EYE = getRegisteredItem("ender_eye");
            SPECKLED_MELON = getRegisteredItem("speckled_melon");
            SPAWN_EGG = getRegisteredItem("spawn_egg");
            EXPERIENCE_BOTTLE = getRegisteredItem("experience_bottle");
            FIRE_CHARGE = getRegisteredItem("fire_charge");
            WRITABLE_BOOK = getRegisteredItem("writable_book");
            WRITTEN_BOOK = getRegisteredItem("written_book");
            EMERALD = getRegisteredItem("emerald");
            ITEM_FRAME = getRegisteredItem("item_frame");
            FLOWER_POT = getRegisteredItem("flower_pot");
            CARROT = getRegisteredItem("carrot");
            POTATO = getRegisteredItem("potato");
            BAKED_POTATO = getRegisteredItem("baked_potato");
            POISONOUS_POTATO = getRegisteredItem("poisonous_potato");
            MAP = (ItemEmptyMap)getRegisteredItem("map");
            GOLDEN_CARROT = getRegisteredItem("golden_carrot");
            SKULL = getRegisteredItem("skull");
            CARROT_ON_A_STICK = getRegisteredItem("carrot_on_a_stick");
            NETHER_STAR = getRegisteredItem("nether_star");
            PUMPKIN_PIE = getRegisteredItem("pumpkin_pie");
            FIREWORKS = getRegisteredItem("fireworks");
            FIREWORK_CHARGE = getRegisteredItem("firework_charge");
            ENCHANTED_BOOK = (ItemEnchantedBook)getRegisteredItem("enchanted_book");
            COMPARATOR = getRegisteredItem("comparator");
            NETHERBRICK = getRegisteredItem("netherbrick");
            QUARTZ = getRegisteredItem("quartz");
            TNT_MINECART = getRegisteredItem("tnt_minecart");
            HOPPER_MINECART = getRegisteredItem("hopper_minecart");
            ARMOR_STAND = (ItemArmorStand)getRegisteredItem("armor_stand");
            IRON_HORSE_ARMOR = getRegisteredItem("iron_horse_armor");
            GOLDEN_HORSE_ARMOR = getRegisteredItem("golden_horse_armor");
            DIAMOND_HORSE_ARMOR = getRegisteredItem("diamond_horse_armor");
            LEAD = getRegisteredItem("lead");
            NAME_TAG = getRegisteredItem("name_tag");
            COMMAND_BLOCK_MINECART = getRegisteredItem("command_block_minecart");
            RECORD_13 = getRegisteredItem("record_13");
            RECORD_CAT = getRegisteredItem("record_cat");
            RECORD_BLOCKS = getRegisteredItem("record_blocks");
            RECORD_CHIRP = getRegisteredItem("record_chirp");
            RECORD_FAR = getRegisteredItem("record_far");
            RECORD_MALL = getRegisteredItem("record_mall");
            RECORD_MELLOHI = getRegisteredItem("record_mellohi");
            RECORD_STAL = getRegisteredItem("record_stal");
            RECORD_STRAD = getRegisteredItem("record_strad");
            RECORD_WARD = getRegisteredItem("record_ward");
            RECORD_11 = getRegisteredItem("record_11");
            RECORD_WAIT = getRegisteredItem("record_wait");
            PRISMARINE_SHARD = getRegisteredItem("prismarine_shard");
            PRISMARINE_CRYSTALS = getRegisteredItem("prismarine_crystals");
            BANNER = getRegisteredItem("banner");
            END_CRYSTAL = getRegisteredItem("end_crystal");
            SHIELD = getRegisteredItem("shield");
            ELYTRA = getRegisteredItem("elytra");
            CHORUS_FRUIT = getRegisteredItem("chorus_fruit");
            CHORUS_FRUIT_POPPED = getRegisteredItem("chorus_fruit_popped");
            BEETROOT_SEEDS = getRegisteredItem("beetroot_seeds");
            BEETROOT = getRegisteredItem("beetroot");
            BEETROOT_SOUP = getRegisteredItem("beetroot_soup");
            // Begin Awaken Dreams code
            LEMBAS = getRegisteredItem("awakendreams:lembas");
            MITHRIL_INGOT = getRegisteredItem("mithril_ingot");
            PIPE = (ItemPipe) getRegisteredItem("pipe");
            BRONZE_INGOT = getRegisteredItem("bronze_ingot");
            TOBACCO = getRegisteredItem("tobacco");
            PIPE.addSmokableItem(TOBACCO);
            JADE = getRegisteredItem("jade");
            AMBER = getRegisteredItem("amber");
            CRYSTAL = getRegisteredItem("crystal");
            AMETHYST = getRegisteredItem("amethyst");
            ONYX = getRegisteredItem("onyx");
            MOONSTONE = getRegisteredItem("moonstone");
            TANZANITE = getRegisteredItem("tanzanite");
            URUK_SWORD = getRegisteredItem("uruk_sword");
            TOMATO = getRegisteredItem("tomato");
            BLUE_FEATHER = getRegisteredItem("blue_feather");
            SPIDER_POISON = getRegisteredItem("spider_poison");
            HERUGRIM = getRegisteredItem("herugrim");
            NUTS = getRegisteredItem("nuts");
            CORN_COB = getRegisteredItem("corn_cob");
            STAFF_BASE = getRegisteredItem("staff_base");
            KNIFE = getRegisteredItem("knife");
            BERRIES = getRegisteredItem("berries");
            BEAR_CLAW = getRegisteredItem("bear_claw");
            BEAST_SKIN = getRegisteredItem("beast_skin");
            DEAD_ROOT = getRegisteredItem("dead_root");
            EAGLE_FEATHER = getRegisteredItem("eagle_feather");
            GOBLIN_EYE = getRegisteredItem("goblin_eye");
            HELEGROG_DEAMON_HEART = getRegisteredItem("helegrog_deamon_heart");
            ORC_BLOOD = getRegisteredItem("orc_blood");
            OWL_FEATHER = getRegisteredItem("owl_feather");
            SCORPION_TAIL = getRegisteredItem("scorpion_tail");
            SHARK_TOOTH = getRegisteredItem("shark_tooth");
            TROLL_SKIN = getRegisteredItem("troll_skin");
            WARG_FANG = getRegisteredItem("warg_fang");
            BLUE_BED = getRegisteredItem("blue_bed");
            Blocks.BLUE_BED.setItem(BLUE_BED);
            BROWN_BED = getRegisteredItem("brown_bed");
            Blocks.BROWN_BED.setItem(BROWN_BED);
            BREE_DOOR = getRegisteredItem("bree_door");
            Blocks.BREE_DOOR.setItem(BREE_DOOR);
            RUCKSACK = getRegisteredItem("rucksack");
            CRAM = getRegisteredItem("cram");
            CABBAGE = getRegisteredItem("cabbage");
            COCONUT = getRegisteredItem("coconut");
            RAW_DEER_MEAT = getRegisteredItem("raw_deer_meat");
            COOKED_DEER_MEAT = getRegisteredItem("cooked_deer_meat");
            MUFFIN = getRegisteredItem("muffin");
            STRAWBERRY = getRegisteredItem("strawberry");
            Blocks.STRAWBERRY_BUSH.setCrop(STRAWBERRY);
            STRAWBERRY_MUFFIN = getRegisteredItem("strawberry_muffin");
            ORANGE = getRegisteredItem("orange");
            ORANGE_MUFFIN = getRegisteredItem("orange_muffin");
            PEAR = getRegisteredItem("pear");
            RAW_MEAT = getRegisteredItem("raw_meat");
            COOKED_MEAT = getRegisteredItem("cooked_meat");
            ROHAN_HELMET_1 = getRegisteredItem("rohan_helmet_1");
            ROHAN_HELMET_2 = getRegisteredItem("rohan_helmet_2");
            ROHAN_HELMET_3 = getRegisteredItem("rohan_helmet_3");
            ROHAN_HELMET_4 = getRegisteredItem("rohan_helmet_4");
            ROHAN_HELMET_5 = getRegisteredItem("rohan_helmet_5");
            ROHAN_HELMET_6 = getRegisteredItem("rohan_helmet_6");
            ROHAN_CHESTPLATE = getRegisteredItem("rohan_chestplate");
            TELESCOPE = getRegisteredItem("telescope");
            HUMAN_DAGGER = getRegisteredItem("human_dagger");
            HOBBIT_DAGGER = getRegisteredItem("hobbit_dagger");
            ELF_DAGGER = getRegisteredItem("elf_dagger");
            GONDORIAN_SWORD = getRegisteredItem("gondorian_sword");
            SOUTHERN_STAR = getRegisteredItem("southern_star");
            Blocks.SOUTHERN_STAR_PLANT.setCrop(SOUTHERN_STAR);
            SOUTHLINCH = getRegisteredItem("southlinch");
            Blocks.SOUTHLINCH.setCrop(SOUTHLINCH);
            OLD_TOBY = getRegisteredItem("old_toby");
            PIPE.addSmokableItem(OLD_TOBY);
            Blocks.OLD_TOBY_PLANT.setCrop(OLD_TOBY);
            STONE_OF_DARKNESS = getRegisteredItem("stone_of_darkness");
            STONE_OF_EARTH = getRegisteredItem("stone_of_earth");
            STONE_OF_FIRE = getRegisteredItem("stone_of_fire");
            STONE_OF_GREED = getRegisteredItem("stone_of_greed");
            STONE_OF_HOPE = getRegisteredItem("stone_of_hope");
            STONE_OF_NATURE = getRegisteredItem("stone_of_nature");
            STONE_OF_SUNLIGHT = getRegisteredItem("stone_of_sunlight");
            STONE_OF_SEA = getRegisteredItem("stone_of_sea");
            STONE_OF_SKY = getRegisteredItem("stone_of_sky");
            STONE_OF_WEALTH = getRegisteredItem("stone_of_wealth");
            STONE_OF_WIND = getRegisteredItem("stone_of_wind");
            HAMMER = getRegisteredItem("hammer");
            GOLD_RING = getRegisteredItem("gold_ring");
            ONYX_GOLD_RING = getRegisteredItem("onyx_gold_ring");
            TANZANITE_GOLD_RING = getRegisteredItem("tanzanite_gold_ring");
            JADE_GOLD_RING = getRegisteredItem("jade_gold_ring");
            MOONSTONE_GOLD_RING = getRegisteredItem("moonstone_gold_ring");
            AMETHYST_GOLD_RING = getRegisteredItem("amethyst_gold_ring");
            RUBY_GOLD_RING = getRegisteredItem("ruby_gold_ring");
            QUARTZ_GOLD_RING = getRegisteredItem("quartz_gold_ring");
            AMBER_GOLD_RING = getRegisteredItem("amber_gold_ring");
            SILVER_RING = getRegisteredItem("silver_ring");
            ONYX_SILVER_RING = getRegisteredItem("onyx_silver_ring");
            TANZANITE_SILVER_RING = getRegisteredItem("tanzanite_silver_ring");
            JADE_SILVER_RING = getRegisteredItem("jade_silver_ring");
            MOONSTONE_SILVER_RING = getRegisteredItem("moonstone_silver_ring");
            AMETHYST_SILVER_RING = getRegisteredItem("amethyst_silver_ring");
            RUBY_SILVER_RING = getRegisteredItem("ruby_silver_ring");
            QUARTZ_SILVER_RING = getRegisteredItem("quartz_silver_ring");
            AMBER_SILVER_RING = getRegisteredItem("amber_silver_ring");
            BRONZE_RING = getRegisteredItem("bronze_ring");
            ONYX_BRONZE_RING = getRegisteredItem("onyx_bronze_ring");
            TANZANITE_BRONZE_RING = getRegisteredItem("tanzanite_bronze_ring");
            JADE_BRONZE_RING = getRegisteredItem("jade_bronze_ring");
            MOONSTONE_BRONZE_RING = getRegisteredItem("moonstone_bronze_ring");
            AMETHYST_BRONZE_RING = getRegisteredItem("amethyst_bronze_ring");
            RUBY_BRONZE_RING = getRegisteredItem("ruby_bronze_ring");
            QUARTZ_BRONZE_RING = getRegisteredItem("quartz_bronze_ring");
            AMBER_BRONZE_RING = getRegisteredItem("amber_bronze_ring");
            MITHRIL_RING = getRegisteredItem("mithril_ring");
            ONYX_MITHRIL_RING = getRegisteredItem("onyx_mithril_ring");
            TANZANITE_MITHRIL_RING = getRegisteredItem("tanzanite_mithril_ring");
            JADE_MITHRIL_RING = getRegisteredItem("jade_mithril_ring");
            MOONSTONE_MITHRIL_RING = getRegisteredItem("moonstone_mithril_ring");
            AMETHYST_MITHRIL_RING = getRegisteredItem("amethyst_mithril_ring");
            RUBY_MITHRIL_RING = getRegisteredItem("ruby_mithril_ring");
            QUARTZ_MITHRIL_RING = getRegisteredItem("quartz_mithril_ring");
            AMBER_MITHRIL_RING = getRegisteredItem("amber_mithril_ring");
            SALT = getRegisteredItem("salt");
            NOLDOR_CHESTPLATE = getRegisteredItem("noldor_chestplate");
            SILVER_INGOT = getRegisteredItem("silver_ingot");
            DWARF_DOOR = getRegisteredItem("dwarf_door");
            Blocks.DWARF_DOOR.setItem(DWARF_DOOR);
            BOROMIRS_SWORD = getRegisteredItem("boromirs_sword");
            ORC_SWORD_1 = getRegisteredItem("orc_sword_1");
            ORC_SWORD_2 = getRegisteredItem("orc_sword_2");
            GOBLIN_SWORD = getRegisteredItem("goblin_sword");
            HOBBIT_AXE = getRegisteredItem("hobbit_axe");
            SHARKUS_SHORTSWORD = getRegisteredItem("sharkus_shortsword");
            BATTLE_PICKAXE = getRegisteredItem("battle_pickaxe");
            SHIRRIFF_CLUB = getRegisteredItem("shirriff_club");
            PIKE_CLUB = getRegisteredItem("pike_club");
            HOBBIT_SWORD = getRegisteredItem("hobbit_sword");
            HOBBIT_HAMMER = getRegisteredItem("hobbit_hammer");
            BOAR_HORNS = getRegisteredItem("boar_horns");
            GOLD_RING_OF_DARKNESS = getRegisteredItem("gold_ring_of_darkness");
            GOLD_RING_OF_EARTH = getRegisteredItem("gold_ring_of_earth");
            GOLD_RING_OF_FIRE = getRegisteredItem("gold_ring_of_fire");
            GOLD_RING_OF_GREED = getRegisteredItem("gold_ring_of_greed");
            GOLD_RING_OF_HOPE = getRegisteredItem("gold_ring_of_hope");
            GOLD_RING_OF_NATURE = getRegisteredItem("gold_ring_of_nature");
            GOLD_RING_OF_SEA = getRegisteredItem("gold_ring_of_sea");
            GOLD_RING_OF_SKY = getRegisteredItem("gold_ring_of_sky");
            GOLD_RING_OF_SUNLIGHT = getRegisteredItem("gold_ring_of_sunlight");
            GOLD_RING_OF_WEALTH = getRegisteredItem("gold_ring_of_wealth");
            GOLD_RING_OF_WIND = getRegisteredItem("gold_ring_of_wind");
            SILVER_RING_OF_DARKNESS = getRegisteredItem("silver_ring_of_darkness");
            SILVER_RING_OF_EARTH = getRegisteredItem("silver_ring_of_earth");
            SILVER_RING_OF_FIRE = getRegisteredItem("silver_ring_of_fire");
            SILVER_RING_OF_GREED = getRegisteredItem("silver_ring_of_greed");
            SILVER_RING_OF_HOPE = getRegisteredItem("silver_ring_of_hope");
            SILVER_RING_OF_NATURE = getRegisteredItem("silver_ring_of_nature");
            SILVER_RING_OF_SEA = getRegisteredItem("silver_ring_of_sea");
            SILVER_RING_OF_SKY = getRegisteredItem("silver_ring_of_sky");
            SILVER_RING_OF_SUNLIGHT = getRegisteredItem("silver_ring_of_sunlight");
            SILVER_RING_OF_WEALTH = getRegisteredItem("silver_ring_of_wealth");
            SILVER_RING_OF_WIND = getRegisteredItem("silver_ring_of_wind");
            BRONZE_RING_OF_DARKNESS = getRegisteredItem("bronze_ring_of_darkness");
            BRONZE_RING_OF_EARTH = getRegisteredItem("bronze_ring_of_earth");
            BRONZE_RING_OF_FIRE = getRegisteredItem("bronze_ring_of_fire");
            BRONZE_RING_OF_GREED = getRegisteredItem("bronze_ring_of_greed");
            BRONZE_RING_OF_HOPE = getRegisteredItem("bronze_ring_of_hope");
            BRONZE_RING_OF_NATURE = getRegisteredItem("bronze_ring_of_nature");
            BRONZE_RING_OF_SEA = getRegisteredItem("bronze_ring_of_sea");
            BRONZE_RING_OF_SKY = getRegisteredItem("bronze_ring_of_sky");
            BRONZE_RING_OF_SUNLIGHT = getRegisteredItem("bronze_ring_of_sunlight");
            BRONZE_RING_OF_WEALTH = getRegisteredItem("bronze_ring_of_wealth");
            BRONZE_RING_OF_WIND = getRegisteredItem("bronze_ring_of_wind");
            MITHRIL_RING_OF_DARKNESS = getRegisteredItem("mithril_ring_of_darkness");
            MITHRIL_RING_OF_EARTH = getRegisteredItem("mithril_ring_of_earth");
            MITHRIL_RING_OF_FIRE = getRegisteredItem("mithril_ring_of_fire");
            MITHRIL_RING_OF_GREED = getRegisteredItem("mithril_ring_of_greed");
            MITHRIL_RING_OF_HOPE = getRegisteredItem("mithril_ring_of_hope");
            MITHRIL_RING_OF_NATURE = getRegisteredItem("mithril_ring_of_nature");
            MITHRIL_RING_OF_SEA = getRegisteredItem("mithril_ring_of_sea");
            MITHRIL_RING_OF_SKY = getRegisteredItem("mithril_ring_of_sky");
            MITHRIL_RING_OF_SUNLIGHT = getRegisteredItem("mithril_ring_of_sunlight");
            MITHRIL_RING_OF_WEALTH = getRegisteredItem("mithril_ring_of_wealth");
            MITHRIL_RING_OF_WIND = getRegisteredItem("mithril_ring_of_wind");
            ANDURIL = getRegisteredItem("anduril");
            MORGUL_SWORD = getRegisteredItem("morgul_sword");
            ELVEN_LONG_SWORD = getRegisteredItem("elven_long_sword");
            BERSERKER_SWORD = getRegisteredItem("berserker_sword");
            TWO_HANDED_SWORD = getRegisteredItem("two_handed_sword");
            THROWING_STONE = getRegisteredItem("throwing_stone");
            ROHIRRIM_AXE = getRegisteredItem("rohirrim_axe");
            ELVEN_DOOR = getRegisteredItem("elven_door");
            Blocks.ELVEN_DOOR.setItem(ELVEN_DOOR);
            HUMAN_DOOR = getRegisteredItem("human_door");
            Blocks.HUMAN_DOOR.setItem(HUMAN_DOOR);
            GREEN_BED = getRegisteredItem("green_bed");
            Blocks.GREEN_BED.setItem(GREEN_BED);
            AICANAR = getRegisteredItem("aicanar");
            BALINS_SWORD = getRegisteredItem("balins_sword");
            BIFURS_SPEAR = getRegisteredItem("bifurs_spear");
            BOMBURS_SPOON = getRegisteredItem("bomburs_spoon");
            DORIS_SWORD = getRegisteredItem("doris_sword");
            DWALINS_AXE = getRegisteredItem("dwalins_axe");
            FILIS_KNIFE = getRegisteredItem("filis_knife");
            FILIS_SWORD = getRegisteredItem("filis_sword");
            KILIS_SWORD = getRegisteredItem("kilis_sword");
            NORIS_CLUB = getRegisteredItem("noris_club");
            OINS_STAFF = getRegisteredItem("oins_staff");
            ORCRIST = getRegisteredItem("orcrist");
            SWORD_OF_WESTERNESSE = getRegisteredItem("sword_of_westernesse");
            THORINS_SWORD = getRegisteredItem("thorins_sword");
            THRAINS_WAR_HAMMER = getRegisteredItem("thrains_war_hammer");
            THRORS_WAR_HAMMER = getRegisteredItem("thrors_war_hammer");
            ARAGORNS_ELF_KNIFE = getRegisteredItem("aragorns_elf_knife");
            EOWYNS_SWORD = getRegisteredItem("eowyns_sword");
            GANDALF_THE_GREYS_STAFF = getRegisteredItem("gandalf_the_greys_staff");
            GANDALF_THE_WHITES_STAFF = getRegisteredItem("gandalf_the_whites_staff");
            GIMLIS_TWO_HEADED_AXE = getRegisteredItem("gimlis_two_headed_axe");
            GIMLIS_LONGAXE = getRegisteredItem("gimlis_longaxe");
            GLAMDRING = getRegisteredItem("glamdring");
            GLOINS_AXE = getRegisteredItem("gloins_axe");
            GLORFINDELS_SWORD = getRegisteredItem("glorfindels_sword");
            GUTHWINE = getRegisteredItem("guthwine");
            HADHAFANG = getRegisteredItem("hadhafang");
            LEGOLAS_SWORD = getRegisteredItem("legolas_sword");
            RADAGASTS_STAFF = getRegisteredItem("radagasts_staff");
            LURTZ_SWORD = getRegisteredItem("lurtz_sword");
            SAURONS_MACE = getRegisteredItem("saurons_mace");
            SARUMANS_STAFF = getRegisteredItem("sarumans_staff");
            YAZNEGS_AXE = getRegisteredItem("yaznegs_axe");
            DWARVEN_LORD_KNIFE = getRegisteredItem("dwarven_lord_knife");
            GONDORIAN_NOBLE_SWORD = getRegisteredItem("gondorian_noble_sword");
            MACE_OF_GLORY = getRegisteredItem("mace_of_glory");
            GOLDEN_WAR_HAMMER_OF_EREBOR = getRegisteredItem("golden_war_hammer_of_erebor");
            GONDORIAN_SPEAR = getRegisteredItem("gondorian_spear");
            ROHIRRIM_SPEAR = getRegisteredItem("rohirrim_spear");
            BULL_HEAD_MACE = getRegisteredItem("bull_head_mace");
            CORSAIR_EKET = getRegisteredItem("corsair_eket");
            DOL_GULDUR_SPIKED_MACE = getRegisteredItem("dol_guldur_spiked_mace");
            FELL_WARGRIDER_SWORD = getRegisteredItem("fell_wargrider_sword");
            HARADRIM_SNAKE_DAGGER = getRegisteredItem("haradrim_snake_dagger");
            NORTH_GOBLIN_MACE = getRegisteredItem("north_goblin_mace");
            NORTH_GOBLIN_SWORD = getRegisteredItem("north_goblin_sword");
            ORC_CAPTAIN_SWORD = getRegisteredItem("orc_captain_sword");
            ORC_DAGGER = getRegisteredItem("orc_dagger");
            ORC_HALBARD = getRegisteredItem("orc_halbard");
            URUK_SIEGE_TROOPER_DAGGER = getRegisteredItem("uruk_siege_trooper_dagger");
            IRON_MACE = getRegisteredItem("iron_mace");
            ORC_SWORD_3 = getRegisteredItem("orc_sword_3");
            MORANNON_DAGGER = getRegisteredItem("morannon_dagger");
            ORC_SPEAR = getRegisteredItem("orc_spear");
            CASTLE_DOOR = getRegisteredItem("castle_door");
            Blocks.CASTLE_DOOR.setItem(CASTLE_DOOR);
            DOL_GULDUR_PRISON_DOOR = getRegisteredItem("dol_guldur_prison_door");
            Blocks.DOL_GULDUR_PRISON_DOOR.setItem(DOL_GULDUR_PRISON_DOOR);
            HILLMEN_DOOR = getRegisteredItem("hillmen_door");
            Blocks.HILLMEN_DOOR.setItem(HILLMEN_DOOR);
            MORDOR_DOOR = getRegisteredItem("mordor_door");
            Blocks.MORDOR_DOOR.setItem(MORDOR_DOOR);
            PRISON_DOOR = getRegisteredItem("prison_door");
            Blocks.PRISON_DOOR.setItem(PRISON_DOOR);
            SINDAR_DOOR = getRegisteredItem("sindar_door");
            Blocks.SINDAR_DOOR.setItem(SINDAR_DOOR);
            SOUTHLINCH_SEED = getRegisteredItem("southlinch_seed");
            Blocks.SOUTHLINCH.setSeed(SOUTHLINCH_SEED);
            GREEN_GRAPE_SEED = getRegisteredItem("green_grape_seed");
            Blocks.GREEN_GRAPE.setSeed(GREEN_GRAPE_SEED);
            GREEN_GRAPES = getRegisteredItem("green_grapes");
            Blocks.GREEN_GRAPE.setCrop(GREEN_GRAPES);
            PURPLE_GRAPE_SEED = getRegisteredItem("purple_grape_seed");
            Blocks.PURPLE_GRAPE.setSeed(PURPLE_GRAPE_SEED);
            PURPLE_GRAPES = getRegisteredItem("purple_grapes");
            Blocks.PURPLE_GRAPE.setCrop(PURPLE_GRAPES);
            PIPEWEED_SEED = getRegisteredItem("pipeweed_seed");
            Blocks.PIPEWEED_PLANT.setSeed(PIPEWEED_SEED);
            PEAS = getRegisteredItem("peas");
            Blocks.PEA_PLANT.setSeed(PEAS);
            PEA_POD = getRegisteredItem("pea_pod");
            Blocks.PEA_PLANT.setCrop(PEA_POD);
            LEEK = getRegisteredItem("leek");
            Blocks.LEEK_PLANT.setCrop(LEEK);
            LEEK_SEED = getRegisteredItem("leek_seed");
            Blocks.LEEK_PLANT.setSeed(LEEK_SEED);
            ONION_SEED = getRegisteredItem("onion_seed");
            Blocks.ONION_PLANT.setSeed(ONION_SEED);
            ONION = getRegisteredItem("onion");
            Blocks.ONION_PLANT.setCrop(ONION);
            OLD_TOBY_SEED = getRegisteredItem("old_toby_seed");
            Blocks.OLD_TOBY_PLANT.setSeed(OLD_TOBY_SEED);
            SOUTHERN_STAR_SEED = getRegisteredItem("southern_star_seed");
            Blocks.SOUTHERN_STAR_PLANT.setSeed(SOUTHERN_STAR_SEED);
            STRAWBERRY_SEED = getRegisteredItem("strawberry_seed");
            Blocks.STRAWBERRY_BUSH.setSeed(STRAWBERRY_SEED);
            ROHAN_BOOTS = getRegisteredItem("rohan_boots");
            ROHAN_LEGGINGS = getRegisteredItem("rohan_leggings");
            RING = getRegisteredItem("ring");
            ELVEN_STEEL_INGOT = getRegisteredItem("elven_steel_ingot");
            // End Awaken Dreams code
        }
    }
}
