package net.minecraft.init;

import net.minecraft.item.Item;
import net.minecraft.item.ItemArmor;
import net.minecraft.item.ItemArmorStand;
import net.minecraft.item.ItemBow;
import net.minecraft.item.ItemEmptyMap;
import net.minecraft.item.ItemEnchantedBook;
import net.minecraft.item.ItemFishingRod;
import net.minecraft.item.ItemMap;
import net.minecraft.item.ItemPotion;
import net.minecraft.item.ItemShears;
import net.minecraft.util.ResourceLocation;

public class Items
{
    public static final Item IRON_SHOVEL;
    public static final Item IRON_PICKAXE;
    public static final Item IRON_AXE;
    public static final Item FLINT_AND_STEEL;
    public static final Item APPLE;
    public static final ItemBow BOW;
    public static final Item ARROW;
    public static final Item SPECTRAL_ARROW;
    public static final Item TIPPED_ARROW;
    public static final Item COAL;
    public static final Item DIAMOND;
    public static final Item IRON_INGOT;
    public static final Item GOLD_INGOT;
    public static final Item IRON_SWORD;
    public static final Item WOODEN_SWORD;
    public static final Item WOODEN_SHOVEL;
    public static final Item WOODEN_PICKAXE;
    public static final Item WOODEN_AXE;
    public static final Item STONE_SWORD;
    public static final Item STONE_SHOVEL;
    public static final Item STONE_PICKAXE;
    public static final Item STONE_AXE;
    public static final Item DIAMOND_SWORD;
    public static final Item DIAMOND_SHOVEL;
    public static final Item DIAMOND_PICKAXE;
    public static final Item DIAMOND_AXE;
    public static final Item STICK;
    public static final Item BOWL;
    public static final Item MUSHROOM_STEW;
    public static final Item GOLDEN_SWORD;
    public static final Item GOLDEN_SHOVEL;
    public static final Item GOLDEN_PICKAXE;
    public static final Item GOLDEN_AXE;
    public static final Item STRING;
    public static final Item FEATHER;
    public static final Item GUNPOWDER;
    public static final Item WOODEN_HOE;
    public static final Item STONE_HOE;
    public static final Item IRON_HOE;
    public static final Item DIAMOND_HOE;
    public static final Item GOLDEN_HOE;
    public static final Item WHEAT_SEEDS;
    public static final Item WHEAT;
    public static final Item BREAD;
    public static final ItemArmor LEATHER_HELMET;
    public static final ItemArmor LEATHER_CHESTPLATE;
    public static final ItemArmor LEATHER_LEGGINGS;
    public static final ItemArmor LEATHER_BOOTS;
    public static final ItemArmor CHAINMAIL_HELMET;
    public static final ItemArmor CHAINMAIL_CHESTPLATE;
    public static final ItemArmor CHAINMAIL_LEGGINGS;
    public static final ItemArmor CHAINMAIL_BOOTS;
    public static final ItemArmor IRON_HELMET;
    public static final ItemArmor IRON_CHESTPLATE;
    public static final ItemArmor IRON_LEGGINGS;
    public static final ItemArmor IRON_BOOTS;
    public static final ItemArmor DIAMOND_HELMET;
    public static final ItemArmor DIAMOND_CHESTPLATE;
    public static final ItemArmor DIAMOND_LEGGINGS;
    public static final ItemArmor DIAMOND_BOOTS;
    public static final ItemArmor GOLDEN_HELMET;
    public static final ItemArmor GOLDEN_CHESTPLATE;
    public static final ItemArmor GOLDEN_LEGGINGS;
    public static final ItemArmor GOLDEN_BOOTS;
    public static final Item FLINT;
    public static final Item PORKCHOP;
    public static final Item COOKED_PORKCHOP;
    public static final Item PAINTING;
    public static final Item GOLDEN_APPLE;
    public static final Item SIGN;
    public static final Item OAK_DOOR;
    public static final Item SPRUCE_DOOR;
    public static final Item BIRCH_DOOR;
    public static final Item JUNGLE_DOOR;
    public static final Item ACACIA_DOOR;
    public static final Item DARK_OAK_DOOR;
    public static final Item BUCKET;
    public static final Item WATER_BUCKET;
    public static final Item LAVA_BUCKET;
    public static final Item MINECART;
    public static final Item SADDLE;
    public static final Item IRON_DOOR;
    public static final Item REDSTONE;
    public static final Item SNOWBALL;
    public static final Item BOAT;
    public static final Item SPRUCE_BOAT;
    public static final Item BIRCH_BOAT;
    public static final Item JUNGLE_BOAT;
    public static final Item ACACIA_BOAT;
    public static final Item DARK_OAK_BOAT;
    public static final Item LEATHER;
    public static final Item MILK_BUCKET;
    public static final Item BRICK;
    public static final Item CLAY_BALL;
    public static final Item REEDS;
    public static final Item PAPER;
    public static final Item BOOK;
    public static final Item SLIME_BALL;
    public static final Item CHEST_MINECART;
    public static final Item FURNACE_MINECART;
    public static final Item EGG;
    public static final Item COMPASS;
    public static final ItemFishingRod FISHING_ROD;
    public static final Item CLOCK;
    public static final Item GLOWSTONE_DUST;
    public static final Item FISH;
    public static final Item COOKED_FISH;
    public static final Item DYE;
    public static final Item BONE;
    public static final Item SUGAR;
    public static final Item CAKE;
    public static final Item BED;
    public static final Item REPEATER;
    public static final Item COOKIE;
    public static final ItemMap FILLED_MAP;
    public static final ItemShears SHEARS;
    public static final Item MELON;
    public static final Item PUMPKIN_SEEDS;
    public static final Item MELON_SEEDS;
    public static final Item BEEF;
    public static final Item COOKED_BEEF;
    public static final Item CHICKEN;
    public static final Item COOKED_CHICKEN;
    public static final Item MUTTON;
    public static final Item COOKED_MUTTON;
    public static final Item RABBIT;
    public static final Item COOKED_RABBIT;
    public static final Item RABBIT_STEW;
    public static final Item RABBIT_FOOT;
    public static final Item RABBIT_HIDE;
    public static final Item ROTTEN_FLESH;
    public static final Item ENDER_PEARL;
    public static final Item BLAZE_ROD;
    public static final Item GHAST_TEAR;
    public static final Item GOLD_NUGGET;
    public static final Item NETHER_WART;
    public static final ItemPotion POTIONITEM;
    public static final ItemPotion SPLASH_POTION;
    public static final ItemPotion LINGERING_POTION;
    public static final Item GLASS_BOTTLE;
    public static final Item DRAGON_BREATH;
    public static final Item SPIDER_EYE;
    public static final Item FERMENTED_SPIDER_EYE;
    public static final Item BLAZE_POWDER;
    public static final Item MAGMA_CREAM;
    public static final Item BREWING_STAND;
    public static final Item CAULDRON;
    public static final Item ENDER_EYE;
    public static final Item SPECKLED_MELON;
    public static final Item SPAWN_EGG;
    public static final Item EXPERIENCE_BOTTLE;
    public static final Item FIRE_CHARGE;
    public static final Item WRITABLE_BOOK;
    public static final Item WRITTEN_BOOK;
    public static final Item EMERALD;
    public static final Item ITEM_FRAME;
    public static final Item FLOWER_POT;
    public static final Item CARROT;
    public static final Item POTATO;
    public static final Item BAKED_POTATO;
    public static final Item POISONOUS_POTATO;
    public static final ItemEmptyMap MAP;
    public static final Item GOLDEN_CARROT;
    public static final Item SKULL;
    public static final Item CARROT_ON_A_STICK;
    public static final Item NETHER_STAR;
    public static final Item PUMPKIN_PIE;
    public static final Item FIREWORKS;
    public static final Item FIREWORK_CHARGE;
    public static final ItemEnchantedBook ENCHANTED_BOOK;
    public static final Item COMPARATOR;
    public static final Item NETHERBRICK;
    public static final Item QUARTZ;
    public static final Item TNT_MINECART;
    public static final Item HOPPER_MINECART;
    public static final ItemArmorStand ARMOR_STAND;
    public static final Item IRON_HORSE_ARMOR;
    public static final Item GOLDEN_HORSE_ARMOR;
    public static final Item DIAMOND_HORSE_ARMOR;
    public static final Item LEAD;
    public static final Item NAME_TAG;
    public static final Item COMMAND_BLOCK_MINECART;
    public static final Item RECORD_13;
    public static final Item RECORD_CAT;
    public static final Item RECORD_BLOCKS;
    public static final Item RECORD_CHIRP;
    public static final Item RECORD_FAR;
    public static final Item RECORD_MALL;
    public static final Item RECORD_MELLOHI;
    public static final Item RECORD_STAL;
    public static final Item RECORD_STRAD;
    public static final Item RECORD_WARD;
    public static final Item RECORD_11;
    public static final Item RECORD_WAIT;
    public static final Item PRISMARINE_SHARD;
    public static final Item PRISMARINE_CRYSTALS;
    public static final Item BANNER;
    public static final Item END_CRYSTAL;
    public static final Item SHIELD;
    public static final Item ELYTRA;
    public static final Item CHORUS_FRUIT;
    public static final Item CHORUS_FRUIT_POPPED;
    public static final Item BEETROOT_SEEDS;
    public static final Item BEETROOT;
    public static final Item BEETROOT_SOUP;
    // Begin Awaken Dreams code
    public static final Item BREE_DOOR;
    public static final Item DWARF_DOOR;
    public static final Item ELVEN_DOOR;
    public static final Item HUMAN_DOOR;
    public static final Item CASTLE_DOOR;
    public static final Item DOL_GULDUR_PRISON_DOOR;
    public static final Item HILLMEN_DOOR;
    public static final Item MORDOR_DOOR;
    public static final Item PRISON_DOOR;
    public static final Item SINDAR_DOOR;
    // End Awaken Dreams code

    private static Item getRegisteredItem(String name)
    {
        Item item = (Item)Item.REGISTRY.getObject(new ResourceLocation(name));

        if (item == null)
        {
            throw new IllegalStateException("Invalid Item requested: " + name);
        }
        else
        {
            return item;
        }
    }

    static
    {
        if (!Bootstrap.isRegistered())
        {
            throw new RuntimeException("Accessed Items before Bootstrap!");
        }
        else
        {
            IRON_SHOVEL = getRegisteredItem("iron_shovel");
            IRON_PICKAXE = getRegisteredItem("iron_pickaxe");
            IRON_AXE = getRegisteredItem("iron_axe");
            FLINT_AND_STEEL = getRegisteredItem("flint_and_steel");
            APPLE = getRegisteredItem("apple");
            BOW = (ItemBow)getRegisteredItem("bow");
            ARROW = getRegisteredItem("arrow");
            SPECTRAL_ARROW = getRegisteredItem("spectral_arrow");
            TIPPED_ARROW = getRegisteredItem("tipped_arrow");
            COAL = getRegisteredItem("coal");
            DIAMOND = getRegisteredItem("diamond");
            IRON_INGOT = getRegisteredItem("iron_ingot");
            GOLD_INGOT = getRegisteredItem("gold_ingot");
            IRON_SWORD = getRegisteredItem("iron_sword");
            WOODEN_SWORD = getRegisteredItem("wooden_sword");
            WOODEN_SHOVEL = getRegisteredItem("wooden_shovel");
            WOODEN_PICKAXE = getRegisteredItem("wooden_pickaxe");
            WOODEN_AXE = getRegisteredItem("wooden_axe");
            STONE_SWORD = getRegisteredItem("stone_sword");
            STONE_SHOVEL = getRegisteredItem("stone_shovel");
            STONE_PICKAXE = getRegisteredItem("stone_pickaxe");
            STONE_AXE = getRegisteredItem("stone_axe");
            DIAMOND_SWORD = getRegisteredItem("diamond_sword");
            DIAMOND_SHOVEL = getRegisteredItem("diamond_shovel");
            DIAMOND_PICKAXE = getRegisteredItem("diamond_pickaxe");
            DIAMOND_AXE = getRegisteredItem("diamond_axe");
            STICK = getRegisteredItem("stick");
            BOWL = getRegisteredItem("bowl");
            MUSHROOM_STEW = getRegisteredItem("mushroom_stew");
            GOLDEN_SWORD = getRegisteredItem("golden_sword");
            GOLDEN_SHOVEL = getRegisteredItem("golden_shovel");
            GOLDEN_PICKAXE = getRegisteredItem("golden_pickaxe");
            GOLDEN_AXE = getRegisteredItem("golden_axe");
            STRING = getRegisteredItem("string");
            FEATHER = getRegisteredItem("feather");
            GUNPOWDER = getRegisteredItem("gunpowder");
            WOODEN_HOE = getRegisteredItem("wooden_hoe");
            STONE_HOE = getRegisteredItem("stone_hoe");
            IRON_HOE = getRegisteredItem("iron_hoe");
            DIAMOND_HOE = getRegisteredItem("diamond_hoe");
            GOLDEN_HOE = getRegisteredItem("golden_hoe");
            WHEAT_SEEDS = getRegisteredItem("wheat_seeds");
            WHEAT = getRegisteredItem("wheat");
            BREAD = getRegisteredItem("bread");
            LEATHER_HELMET = (ItemArmor)getRegisteredItem("leather_helmet");
            LEATHER_CHESTPLATE = (ItemArmor)getRegisteredItem("leather_chestplate");
            LEATHER_LEGGINGS = (ItemArmor)getRegisteredItem("leather_leggings");
            LEATHER_BOOTS = (ItemArmor)getRegisteredItem("leather_boots");
            CHAINMAIL_HELMET = (ItemArmor)getRegisteredItem("chainmail_helmet");
            CHAINMAIL_CHESTPLATE = (ItemArmor)getRegisteredItem("chainmail_chestplate");
            CHAINMAIL_LEGGINGS = (ItemArmor)getRegisteredItem("chainmail_leggings");
            CHAINMAIL_BOOTS = (ItemArmor)getRegisteredItem("chainmail_boots");
            IRON_HELMET = (ItemArmor)getRegisteredItem("iron_helmet");
            IRON_CHESTPLATE = (ItemArmor)getRegisteredItem("iron_chestplate");
            IRON_LEGGINGS = (ItemArmor)getRegisteredItem("iron_leggings");
            IRON_BOOTS = (ItemArmor)getRegisteredItem("iron_boots");
            DIAMOND_HELMET = (ItemArmor)getRegisteredItem("diamond_helmet");
            DIAMOND_CHESTPLATE = (ItemArmor)getRegisteredItem("diamond_chestplate");
            DIAMOND_LEGGINGS = (ItemArmor)getRegisteredItem("diamond_leggings");
            DIAMOND_BOOTS = (ItemArmor)getRegisteredItem("diamond_boots");
            GOLDEN_HELMET = (ItemArmor)getRegisteredItem("golden_helmet");
            GOLDEN_CHESTPLATE = (ItemArmor)getRegisteredItem("golden_chestplate");
            GOLDEN_LEGGINGS = (ItemArmor)getRegisteredItem("golden_leggings");
            GOLDEN_BOOTS = (ItemArmor)getRegisteredItem("golden_boots");
            FLINT = getRegisteredItem("flint");
            PORKCHOP = getRegisteredItem("porkchop");
            COOKED_PORKCHOP = getRegisteredItem("cooked_porkchop");
            PAINTING = getRegisteredItem("painting");
            GOLDEN_APPLE = getRegisteredItem("golden_apple");
            SIGN = getRegisteredItem("sign");
            OAK_DOOR = getRegisteredItem("wooden_door");
            SPRUCE_DOOR = getRegisteredItem("spruce_door");
            BIRCH_DOOR = getRegisteredItem("birch_door");
            JUNGLE_DOOR = getRegisteredItem("jungle_door");
            ACACIA_DOOR = getRegisteredItem("acacia_door");
            DARK_OAK_DOOR = getRegisteredItem("dark_oak_door");
            BUCKET = getRegisteredItem("bucket");
            WATER_BUCKET = getRegisteredItem("water_bucket");
            LAVA_BUCKET = getRegisteredItem("lava_bucket");
            MINECART = getRegisteredItem("minecart");
            SADDLE = getRegisteredItem("saddle");
            IRON_DOOR = getRegisteredItem("iron_door");
            REDSTONE = getRegisteredItem("redstone");
            SNOWBALL = getRegisteredItem("snowball");
            BOAT = getRegisteredItem("boat");
            SPRUCE_BOAT = getRegisteredItem("spruce_boat");
            BIRCH_BOAT = getRegisteredItem("birch_boat");
            JUNGLE_BOAT = getRegisteredItem("jungle_boat");
            ACACIA_BOAT = getRegisteredItem("acacia_boat");
            DARK_OAK_BOAT = getRegisteredItem("dark_oak_boat");
            LEATHER = getRegisteredItem("leather");
            MILK_BUCKET = getRegisteredItem("milk_bucket");
            BRICK = getRegisteredItem("brick");
            CLAY_BALL = getRegisteredItem("clay_ball");
            REEDS = getRegisteredItem("reeds");
            PAPER = getRegisteredItem("paper");
            BOOK = getRegisteredItem("book");
            SLIME_BALL = getRegisteredItem("slime_ball");
            CHEST_MINECART = getRegisteredItem("chest_minecart");
            FURNACE_MINECART = getRegisteredItem("furnace_minecart");
            EGG = getRegisteredItem("egg");
            COMPASS = getRegisteredItem("compass");
            FISHING_ROD = (ItemFishingRod)getRegisteredItem("fishing_rod");
            CLOCK = getRegisteredItem("clock");
            GLOWSTONE_DUST = getRegisteredItem("glowstone_dust");
            FISH = getRegisteredItem("fish");
            COOKED_FISH = getRegisteredItem("cooked_fish");
            DYE = getRegisteredItem("dye");
            BONE = getRegisteredItem("bone");
            SUGAR = getRegisteredItem("sugar");
            CAKE = getRegisteredItem("cake");
            BED = getRegisteredItem("bed");
            REPEATER = getRegisteredItem("repeater");
            COOKIE = getRegisteredItem("cookie");
            FILLED_MAP = (ItemMap)getRegisteredItem("filled_map");
            SHEARS = (ItemShears)getRegisteredItem("shears");
            MELON = getRegisteredItem("melon");
            PUMPKIN_SEEDS = getRegisteredItem("pumpkin_seeds");
            MELON_SEEDS = getRegisteredItem("melon_seeds");
            BEEF = getRegisteredItem("beef");
            COOKED_BEEF = getRegisteredItem("cooked_beef");
            CHICKEN = getRegisteredItem("chicken");
            COOKED_CHICKEN = getRegisteredItem("cooked_chicken");
            MUTTON = getRegisteredItem("mutton");
            COOKED_MUTTON = getRegisteredItem("cooked_mutton");
            RABBIT = getRegisteredItem("rabbit");
            COOKED_RABBIT = getRegisteredItem("cooked_rabbit");
            RABBIT_STEW = getRegisteredItem("rabbit_stew");
            RABBIT_FOOT = getRegisteredItem("rabbit_foot");
            RABBIT_HIDE = getRegisteredItem("rabbit_hide");
            ROTTEN_FLESH = getRegisteredItem("rotten_flesh");
            ENDER_PEARL = getRegisteredItem("ender_pearl");
            BLAZE_ROD = getRegisteredItem("blaze_rod");
            GHAST_TEAR = getRegisteredItem("ghast_tear");
            GOLD_NUGGET = getRegisteredItem("gold_nugget");
            NETHER_WART = getRegisteredItem("nether_wart");
            POTIONITEM = (ItemPotion)getRegisteredItem("potion");
            SPLASH_POTION = (ItemPotion)getRegisteredItem("splash_potion");
            LINGERING_POTION = (ItemPotion)getRegisteredItem("lingering_potion");
            GLASS_BOTTLE = getRegisteredItem("glass_bottle");
            DRAGON_BREATH = getRegisteredItem("dragon_breath");
            SPIDER_EYE = getRegisteredItem("spider_eye");
            FERMENTED_SPIDER_EYE = getRegisteredItem("fermented_spider_eye");
            BLAZE_POWDER = getRegisteredItem("blaze_powder");
            MAGMA_CREAM = getRegisteredItem("magma_cream");
            BREWING_STAND = getRegisteredItem("brewing_stand");
            CAULDRON = getRegisteredItem("cauldron");
            ENDER_EYE = getRegisteredItem("ender_eye");
            SPECKLED_MELON = getRegisteredItem("speckled_melon");
            SPAWN_EGG = getRegisteredItem("spawn_egg");
            EXPERIENCE_BOTTLE = getRegisteredItem("experience_bottle");
            FIRE_CHARGE = getRegisteredItem("fire_charge");
            WRITABLE_BOOK = getRegisteredItem("writable_book");
            WRITTEN_BOOK = getRegisteredItem("written_book");
            EMERALD = getRegisteredItem("emerald");
            ITEM_FRAME = getRegisteredItem("item_frame");
            FLOWER_POT = getRegisteredItem("flower_pot");
            CARROT = getRegisteredItem("carrot");
            POTATO = getRegisteredItem("potato");
            BAKED_POTATO = getRegisteredItem("baked_potato");
            POISONOUS_POTATO = getRegisteredItem("poisonous_potato");
            MAP = (ItemEmptyMap)getRegisteredItem("map");
            GOLDEN_CARROT = getRegisteredItem("golden_carrot");
            SKULL = getRegisteredItem("skull");
            CARROT_ON_A_STICK = getRegisteredItem("carrot_on_a_stick");
            NETHER_STAR = getRegisteredItem("nether_star");
            PUMPKIN_PIE = getRegisteredItem("pumpkin_pie");
            FIREWORKS = getRegisteredItem("fireworks");
            FIREWORK_CHARGE = getRegisteredItem("firework_charge");
            ENCHANTED_BOOK = (ItemEnchantedBook)getRegisteredItem("enchanted_book");
            COMPARATOR = getRegisteredItem("comparator");
            NETHERBRICK = getRegisteredItem("netherbrick");
            QUARTZ = getRegisteredItem("quartz");
            TNT_MINECART = getRegisteredItem("tnt_minecart");
            HOPPER_MINECART = getRegisteredItem("hopper_minecart");
            ARMOR_STAND = (ItemArmorStand)getRegisteredItem("armor_stand");
            IRON_HORSE_ARMOR = getRegisteredItem("iron_horse_armor");
            GOLDEN_HORSE_ARMOR = getRegisteredItem("golden_horse_armor");
            DIAMOND_HORSE_ARMOR = getRegisteredItem("diamond_horse_armor");
            LEAD = getRegisteredItem("lead");
            NAME_TAG = getRegisteredItem("name_tag");
            COMMAND_BLOCK_MINECART = getRegisteredItem("command_block_minecart");
            RECORD_13 = getRegisteredItem("record_13");
            RECORD_CAT = getRegisteredItem("record_cat");
            RECORD_BLOCKS = getRegisteredItem("record_blocks");
            RECORD_CHIRP = getRegisteredItem("record_chirp");
            RECORD_FAR = getRegisteredItem("record_far");
            RECORD_MALL = getRegisteredItem("record_mall");
            RECORD_MELLOHI = getRegisteredItem("record_mellohi");
            RECORD_STAL = getRegisteredItem("record_stal");
            RECORD_STRAD = getRegisteredItem("record_strad");
            RECORD_WARD = getRegisteredItem("record_ward");
            RECORD_11 = getRegisteredItem("record_11");
            RECORD_WAIT = getRegisteredItem("record_wait");
            PRISMARINE_SHARD = getRegisteredItem("prismarine_shard");
            PRISMARINE_CRYSTALS = getRegisteredItem("prismarine_crystals");
            BANNER = getRegisteredItem("banner");
            END_CRYSTAL = getRegisteredItem("end_crystal");
            SHIELD = getRegisteredItem("shield");
            ELYTRA = getRegisteredItem("elytra");
            CHORUS_FRUIT = getRegisteredItem("chorus_fruit");
            CHORUS_FRUIT_POPPED = getRegisteredItem("chorus_fruit_popped");
            BEETROOT_SEEDS = getRegisteredItem("beetroot_seeds");
            BEETROOT = getRegisteredItem("beetroot");
            BEETROOT_SOUP = getRegisteredItem("beetroot_soup");
            // Begin Awaken Dreams code
            /*itemRegistry.addObject(6000, "lembas", (new ItemValarFood(8, 0.8F, false).setUnlocalizedName("lembas").setTextureName("lembas")));
            itemRegistry.addObject(6001, "mithril_ingot", (new ItemValarBase(CreativeTabs.tabMaterials).setUnlocalizedName("mithrilIngot").setTextureName("mithril_ingot")));
            itemRegistry.addObject(6002, "bronze_ingot", (new ItemValarBase(CreativeTabs.tabMaterials).setUnlocalizedName("bronzeIngot").setTextureName("bronze_ingot")));
            itemRegistry.addObject(6003, "pipe", (new ItemValarBase().setUnlocalizedName("pipe").setTextureName("pipe")));
            itemRegistry.addObject(6004, "tobacco", (new ItemValarBase().setUnlocalizedName("tobacco").setTextureName("tobacco")));
            itemRegistry.addObject(6005, "flaming_arrow", (new ItemValarBase().setUnlocalizedName("flamingArrow").setTextureName("flaming_arrow")));
            //itemRegistry.addObject(6006, "requiem_for_a_dream", (new ItemValarBase().setUnlocalizedName("requiemForADream").setTextureName("requiem_for_a_dream")));
            //itemRegistry.addObject(6007, "ruby", (new ItemValarBase().setUnlocalizedName("ruby").setTextureName("ruby")));
            itemRegistry.addObject(6008, "jade", (new ItemValarBase(CreativeTabs.tabMaterials).setUnlocalizedName("jade").setTextureName("jade")));
            itemRegistry.addObject(6009, "amber", (new ItemValarBase(CreativeTabs.tabMaterials).setUnlocalizedName("amber").setTextureName("amber")));
            itemRegistry.addObject(6010, "parchment", (new ItemValarBase().setUnlocalizedName("parchment").setTextureName("parchment")));
            //itemRegistry.addObject(6011, "evenstar_record", (new ItemValarBase().setUnlocalizedName("evenstar_record").setTextureName("evenstar_record")));
            //itemRegistry.addObject(6012, "bridge_of_khazad_dum", (new ItemValarBase().setUnlocalizedName("bridgeOfKhazadDum").setTextureName("bridge_of_khazad_dum")));
            //itemRegistry.addObject(6013, "isengard_unleashed", (new ItemValarBase().setUnlocalizedName("isengardUnleashed").setTextureName("isengard_unleashed")));
            itemRegistry.addObject(6014, "crystal", (new ItemValarBase(CreativeTabs.tabMaterials).setUnlocalizedName("crystal").setTextureName("crystal")));
            itemRegistry.addObject(6015, "amethyst", (new ItemValarBase(CreativeTabs.tabMaterials).setUnlocalizedName("amethyst").setTextureName("amethyst")));
            itemRegistry.addObject(6016, "onyx", (new ItemValarBase(CreativeTabs.tabMaterials).setUnlocalizedName("onyx").setTextureName("onyx")));
            itemRegistry.addObject(6017, "moonstone", (new ItemValarBase(CreativeTabs.tabMaterials).setUnlocalizedName("moonstone").setTextureName("moonstone")));
            //itemRegistry.addObject(6018, "quartz", (new ItemValarBase().setUnlocalizedName("quartz").setTextureName("quartz")));
            itemRegistry.addObject(6019, "tanzanite", (new ItemValarBase(CreativeTabs.tabMaterials).setUnlocalizedName("tanzanite").setTextureName("tanzanite")));
            itemRegistry.addObject(6020, "uruk_sword", (new ItemValarWeapon(510, 7, 0, true, false).setUnlocalizedName("urukSword").setTextureName("uruk_sword")));
            itemRegistry.addObject(6021, "phial_of_galadriel", (new ItemValarBase().setUnlocalizedName("phialOfGaladriel").setTextureName("phial_of_galadriel")));
            itemRegistry.addObject(6022, "tomato", (new ItemValarFood(1, 0.1F, false).setUnlocalizedName("tomato").setTextureName("tomato")));
            itemRegistry.addObject(6023, "blue_feather", (new ItemValarBase(CreativeTabs.tabMaterials).setUnlocalizedName("blueFeather").setTextureName("blue_feather")));
            //itemRegistry.addObject(6024, "rain_stick", (new ItemValarBase().setUnlocalizedName("rainStick").setTextureName("rain_stick")));
            //itemRegistry.addObject(6025, "sun_staff", (new ItemValarBase().setUnlocalizedName("sunStaff").setTextureName("sun_staff")));
            itemRegistry.addObject(6026, "spider_poison", (new ItemValarBase(CreativeTabs.tabMaterials).setUnlocalizedName("spiderPoison").setTextureName("spider_poison")));
            //itemRegistry.addObject(6027, "life_staff", (new ItemValarBase().setUnlocalizedName("lifeStaff").setTextureName("life_staff")));
            itemRegistry.addObject(6028, "herugrim", (new ItemValarWeapon(830, 7, 0, true, false).setUnlocalizedName("herugrim").setTextureName("herugrim")));
            itemRegistry.addObject(6029, "nuts", (new ItemValarFood(1, 0.2F, false).setUnlocalizedName("nuts").setTextureName("nuts")));
            // SPOTS 6030-6031 FREE
            itemRegistry.addObject(6032, "corn_cob", (new ItemValarFood(2, 0.3F, false).setUnlocalizedName("cornCob").setTextureName("corn_cob")));
            //itemRegistry.addObject(6033, "healing_staff", (new ItemValarBase().setUnlocalizedName("healingStaff").setTextureName("healing_staff")));
            //itemRegistry.addObject(6034, "lightning_rod", (new ItemValarBase().setUnlocalizedName("lightningRod").setTextureName("lightning_rod")));
            itemRegistry.addObject(6035, "staff_base", (new ItemValarBase().setUnlocalizedName("staffBase").setTextureName("staff_base")));
            itemRegistry.addObject(6036, "knife", (new ItemValarWeapon(35, 4, 0, true, false).setUnlocalizedName("knife").setTextureName("knife")));
            //itemRegistry.addObject(6037, "mana_bottle", (new ItemValarBase().setUnlocalizedName("manaBottle").setTextureName("mana_bottle")));
            itemRegistry.addObject(6038, "berries", (new ItemValarFood(2, 0.3F, false).setUnlocalizedName("berries").setTextureName("berries")));
            itemRegistry.addObject(6039, "gondorian_horn", (new ItemValarInstrument("").setUnlocalizedName("gondorianHorn").setTextureName("gondorian_horn")));
            itemRegistry.addObject(6040, "bear_claw", (new ItemValarBase(CreativeTabs.tabMaterials).setUnlocalizedName("bearClaw").setTextureName("bear_claw")));
            itemRegistry.addObject(6041, "beast_skin", (new ItemValarBase(CreativeTabs.tabMaterials).setUnlocalizedName("beastSkin").setTextureName("beast_skin")));
            itemRegistry.addObject(6042, "dead_root", (new ItemValarBase(CreativeTabs.tabMaterials).setUnlocalizedName("deadRoot").setTextureName("dead_root")));
            itemRegistry.addObject(6043, "eagle_feather", (new ItemValarBase(CreativeTabs.tabMaterials).setUnlocalizedName("eagleFeather").setTextureName("eagle_feather")));
            itemRegistry.addObject(6044, "goblin_eye", (new ItemValarBase(CreativeTabs.tabMaterials).setUnlocalizedName("goblinEye").setTextureName("goblin_eye")));
            itemRegistry.addObject(6045, "helegrog_deamon_heart", (new ItemValarBase(CreativeTabs.tabMaterials).setUnlocalizedName("helegrogDeamonHeart").setTextureName("helegrog_deamon_heart")));
            itemRegistry.addObject(6046, "orc_blood", (new ItemValarBase(CreativeTabs.tabMaterials).setUnlocalizedName("orcBlood").setTextureName("orc_blood")));
            itemRegistry.addObject(6047, "owl_feather", (new ItemValarBase(CreativeTabs.tabMaterials).setUnlocalizedName("owlFeather").setTextureName("owl_feather")));
            itemRegistry.addObject(6048, "scorpion_tail", (new ItemValarBase(CreativeTabs.tabMaterials).setUnlocalizedName("scorpionTail").setTextureName("scorpion_tail")));
            itemRegistry.addObject(6049, "shark_tooth", (new ItemValarBase(CreativeTabs.tabMaterials).setUnlocalizedName("sharkTooth").setTextureName("shark_tooth")));
            itemRegistry.addObject(6050, "troll_skin", (new ItemValarBase(CreativeTabs.tabMaterials).setUnlocalizedName("trollSkin").setTextureName("troll_skin")));
            itemRegistry.addObject(6051, "warg_fang", (new ItemValarBase(CreativeTabs.tabMaterials).setUnlocalizedName("wargFang").setTextureName("warg_fang")));
            itemRegistry.addObject(6052, "blue_bed_item", (new ItemValarBed((BlockValarBed)Blocks.blueBed).setUnlocalizedName("blueBedItem").setTextureName("blue_bed_item")));
            itemRegistry.addObject(6053, "brown_bed_item", (new ItemValarBed((BlockValarBed)Blocks.brownBed).setUnlocalizedName("brownBedItem").setTextureName("brown_bed_item")));
            itemRegistry.addObject(6054, "brown_hobbit_hat", (new ItemValarArmor(0, 1, 55, 0).setUnlocalizedName("brownHobbitHat").setTextureName("brown_hobbit_hat")));
            itemRegistry.addObject(6055, "orc_helmet", (new ItemValarArmor(0, 1, 200, 0).setUnlocalizedName("orcHelmet").setTextureName("orc_helmet")));*/
            BREE_DOOR = getRegisteredItem("bree_door");
            DWARF_DOOR = getRegisteredItem("dwarf_door");
            //itemRegistry.addObject(6057, "rucksack", (new ItemValarBase().setUnlocalizedName("rucksack").setTextureName("rucksack")));
            /*itemRegistry.addObject(6058, "cram", (new ItemValarFood(2, 0.8F, false).setUnlocalizedName("cram").setTextureName("cram")));
            itemRegistry.addObject(6059, "cabbage", (new ItemValarFood(3, 0.6F, false).setUnlocalizedName("cabbage").setTextureName("cabbage")));
            itemRegistry.addObject(6060, "coconut", (new ItemValarFood(1, 0.3F, false).setUnlocalizedName("coconut").setTextureName("coconut")));
            itemRegistry.addObject(6061, "raw_deer_meat", (new ItemValarFood(3, 0.4F, false).setUnlocalizedName("rawDeerMeat").setTextureName("raw_deer_meat")));
            itemRegistry.addObject(6062, "cooked_deer_meat", (new ItemValarFood(5, 0.6F, false).setUnlocalizedName("cookedDeerMeat").setTextureName("cooked_deer_meat")));
            itemRegistry.addObject(6063, "muffin", (new ItemValarFood(1, 0.4F, false).setUnlocalizedName("muffin").setTextureName("muffin")));
            itemRegistry.addObject(6064, "strawberry", (new ItemValarFood(2, 0.3F, false).setUnlocalizedName("strawberry").setTextureName("strawberry")));
            itemRegistry.addObject(6065, "strawberry_muffin", (new ItemValarFood(3, 0.6F, false).setUnlocalizedName("strawberryMuffin").setTextureName("strawberry_muffin")));
            itemRegistry.addObject(6066, "orange", (new ItemValarFood(2, 0.6F, false).setUnlocalizedName("orange").setTextureName("orange")));
            itemRegistry.addObject(6067, "orange_muffin", (new ItemValarFood(3, 0.6F, false).setUnlocalizedName("orangeMuffin").setTextureName("orange_muffin")));
            itemRegistry.addObject(6068, "pear", (new ItemValarFood(2, 0.6F, false).setUnlocalizedName("pear").setTextureName("pear")));
            itemRegistry.addObject(6069, "raw_meat", (new ItemValarFood(2, 0.2F, false).setUnlocalizedName("rawMeat").setTextureName("raw_meat")));
            itemRegistry.addObject(6070, "cooked_meat", (new ItemValarFood(5, 0.7F, false).setUnlocalizedName("cookedMeat").setTextureName("cooked_meat")));
            itemRegistry.addObject(6071, "rohan_helm_1", (new ItemValarBase().setUnlocalizedName("rohanHelm1").setTextureName("rohan_helm_1")));
            itemRegistry.addObject(6072, "rohan_helm_2", (new ItemValarBase().setUnlocalizedName("rohanHelm2").setTextureName("rohan_helm_2")));
            itemRegistry.addObject(6073, "rohan_helm_3", (new ItemValarBase().setUnlocalizedName("rohanHelm3").setTextureName("rohan_helm_3")));
            itemRegistry.addObject(6074, "rohan_helm_4", (new ItemValarBase().setUnlocalizedName("rohanHelm4").setTextureName("rohan_helm_4")));
            itemRegistry.addObject(6075, "rohan_helm_5", (new ItemValarBase().setUnlocalizedName("rohanHelm5").setTextureName("rohan_helm_5")));
            itemRegistry.addObject(6076, "rohan_helm_6", (new ItemValarBase().setUnlocalizedName("rohanHelm6").setTextureName("rohan_helm_6")));
            itemRegistry.addObject(6077, "rohan_chestplate", (new ItemValarBase().setUnlocalizedName("rohanChestplate").setTextureName("rohan_chestplate")));
            //itemRegistry.addObject(6078, "crossbow", (new ItemValarBase().setUnlocalizedName("crossbow").setTextureName("crossbow")));
            //itemRegistry.addObject(6079, "crossbow_bolt", (new ItemValarBase().setUnlocalizedName("crossbowBolt").setTextureName("crossbow_bolt")));
            itemRegistry.addObject(6080, "telescope", (new ItemValarTelescope().setUnlocalizedName("telescope").setTextureName("telescope")));
            itemRegistry.addObject(6081, "stone_inscription", (new ItemValarStoneInscription()).setUnlocalizedName("stoneInscription").setTextureName("stone_inscription"));
            itemRegistry.addObject(6082, "sting", (new ItemValarSting().setUnlocalizedName("sting").setTextureName("sting")));
            //itemRegistry.addObject(6083, "into_the_west", (new ItemValarBase().setUnlocalizedName("intotheWest").setTextureName("into_the_west")));
            //itemRegistry.addObject(6084, "may_it_be", (new ItemValarBase().setUnlocalizedName("mayItBe").setTextureName("may_it_be")));
            itemRegistry.addObject(6085, "human_dagger", (new ItemValarWeapon(50, 4).setUnlocalizedName("humanDagger").setTextureName("human_dagger")));
            itemRegistry.addObject(6086, "hobbit_dagger", (new ItemValarWeapon(50, 4).setUnlocalizedName("hobbitDagger").setTextureName("hobbit_dagger")));
            itemRegistry.addObject(6087, "elf_dagger", (new ItemValarWeapon(80, 5).setUnlocalizedName("elfDagger").setTextureName("elf_dagger")));
            itemRegistry.addObject(6088, "gondorian_sword", (new ItemValarWeapon(350, 6).setUnlocalizedName("gondorianSword").setTextureName("gondorian_sword")));
            itemRegistry.addObject(6089, "broken_narsil", (new ItemValarWeapon(2000, 10).setUnlocalizedName("brokenNarsil").setTextureName("broken_narsil")));
            //itemRegistry.addObject(6090, "poison_potion", (new ItemValarBase().setUnlocalizedName("poisonPotion").setTextureName("poison_potion")));
            //itemRegistry.addObject(6091, "healing_potion", (new ItemValarBase().setUnlocalizedName("healingPotion").setTextureName("healing_potion")));
            //itemRegistry.addObject(6092, "light_blue_potion", (new ItemValarBase().setUnlocalizedName("lightBluePotion").setTextureName("light_blue_potion")));
            //itemRegistry.addObject(6093, "miruvor", (new ItemValarBase().setUnlocalizedName("miruvor").setTextureName("miruvor")));
            //itemRegistry.addObject(6094, "orange_potion", (new ItemValarBase().setUnlocalizedName("orangePotion").setTextureName("orange_potion")));
            //itemRegistry.addObject(6095, "red_potion", (new ItemValarBase().setUnlocalizedName("redPotion").setTextureName("red_potion")));
            //itemRegistry.addObject(6096, "yellow_potion", (new ItemValarBase().setUnlocalizedName("yellowPotion").setTextureName("yellow_potion")));
            itemRegistry.addObject(6097, "southern_star", (new ItemValarBase().setUnlocalizedName("southernStar").setTextureName("southern_star")));
            itemRegistry.addObject(6098, "south_linch", (new ItemValarBase().setUnlocalizedName("southLinch").setTextureName("south_linch")));
            itemRegistry.addObject(6099, "gondorian_tobacco", (new ItemValarBase().setUnlocalizedName("gondorianTobacco").setTextureName("gondorian_tobacco")));
            itemRegistry.addObject(6100, "longbottom_leaf", (new ItemValarBase().setUnlocalizedName("longbottomLeaf").setTextureName("longbottom_leaf")));
            // Temporary break (remove this comment if you do not know what it is)
            itemRegistry.addObject(6101, "old_toby", (new ItemValarBase().setUnlocalizedName("oldToby").setTextureName("old_toby")));
            itemRegistry.addObject(6102, "brown_pipe", (new ItemValarBase().setUnlocalizedName("brownPipe").setTextureName("brown_pipe")));
            itemRegistry.addObject(6103, "stone_of_darkness", (new ItemValarBase().setUnlocalizedName("stoneOfDarkness").setTextureName("stone_of_darkness")));
            itemRegistry.addObject(6104, "stone_of_earth", (new ItemValarBase().setUnlocalizedName("stoneOfEarth").setTextureName("stone_of_earth")));
            itemRegistry.addObject(6105, "stone_of_fire", (new ItemValarBase().setUnlocalizedName("stoneOfFire").setTextureName("stone_of_fire")));
            itemRegistry.addObject(6106, "stone_of_greed", (new ItemValarBase().setUnlocalizedName("stoneOfGreed").setTextureName("stone_of_greed")));
            itemRegistry.addObject(6107, "stone_of_hope", (new ItemValarBase().setUnlocalizedName("stoneOfHope").setTextureName("stone_of_hope")));
            itemRegistry.addObject(6108, "stone_of_nature", (new ItemValarBase().setUnlocalizedName("stoneOfNature").setTextureName("stone_of_nature")));
            itemRegistry.addObject(6109, "stone_of_sunlight", (new ItemValarBase().setUnlocalizedName("stoneOfSunlight").setTextureName("stone_of_sunlight")));
            itemRegistry.addObject(6110, "stone_of_sea", (new ItemValarBase().setUnlocalizedName("stoneOfSea").setTextureName("stone_of_sea")));
            itemRegistry.addObject(6111, "stone_of_sky", (new ItemValarBase().setUnlocalizedName("stoneOfSky").setTextureName("stone_of_sky")));
            itemRegistry.addObject(6112, "stone_of_wealth", (new ItemValarBase().setUnlocalizedName("stoneOfWealth").setTextureName("stone_of_wealth")));
            itemRegistry.addObject(6113, "stone_of_wind", (new ItemValarBase().setUnlocalizedName("stoneOfWind").setTextureName("stone_of_wind")));
            itemRegistry.addObject(6114, "hammer", (new ItemValarBase().setUnlocalizedName("hammer").setTextureName("hammer")));
            itemRegistry.addObject(6115, "gold_ring", (new ItemValarBase().setUnlocalizedName("goldRing").setTextureName("gold_ring")));
            itemRegistry.addObject(6116, "onyx_gold_ring", (new ItemValarBase().setUnlocalizedName("onyxGoldRing").setTextureName("onyx_gold_ring")));
            itemRegistry.addObject(6117, "tanzanite_gold_ring", (new ItemValarBase().setUnlocalizedName("tanzaniteGoldRing").setTextureName("tanzanite_gold_ring")));
            itemRegistry.addObject(6118, "jade_gold_ring", (new ItemValarBase().setUnlocalizedName("jadeGoldRing").setTextureName("jade_gold_ring")));
            itemRegistry.addObject(6119, "moonstone_gold_ring", (new ItemValarBase().setUnlocalizedName("moonstoneGoldRing").setTextureName("moonstone_gold_ring")));
            itemRegistry.addObject(6120, "amethyst_gold_ring", (new ItemValarBase().setUnlocalizedName("amethystGoldRing").setTextureName("amethyst_gold_ring")));
            itemRegistry.addObject(6121, "ruby_gold_ring", (new ItemValarBase().setUnlocalizedName("rubyGoldRing").setTextureName("ruby_gold_ring")));
            itemRegistry.addObject(6122, "quartz_gold_ring", (new ItemValarBase().setUnlocalizedName("quartzGoldRing").setTextureName("quartz_gold_ring")));
            itemRegistry.addObject(6123, "amber_gold_ring", (new ItemValarBase().setUnlocalizedName("amberGoldRing").setTextureName("amber_gold_ring")));
            itemRegistry.addObject(6124, "silver_ring", (new ItemValarBase().setUnlocalizedName("silverRing").setTextureName("silver_ring")));
            itemRegistry.addObject(6125, "onyx_silver_ring", (new ItemValarBase().setUnlocalizedName("onyxSilverRing").setTextureName("onyx_silver_ring")));
            itemRegistry.addObject(6126, "tanzanite_silver_ring", (new ItemValarBase().setUnlocalizedName("tanzaniteSilverRing").setTextureName("tanzanite_silver_ring")));
            itemRegistry.addObject(6127, "jade_silver_ring", (new ItemValarBase().setUnlocalizedName("jadeSilverRing").setTextureName("jade_silver_ring")));
            itemRegistry.addObject(6128, "moonstone_silver_ring", (new ItemValarBase().setUnlocalizedName("moonstoneSilverRing").setTextureName("moonstone_silver_ring")));
            itemRegistry.addObject(6129, "amethyst_silver_ring", (new ItemValarBase().setUnlocalizedName("amethystSilverRing").setTextureName("amethyst_silver_ring")));
            itemRegistry.addObject(6130, "ruby_silver_ring", (new ItemValarBase().setUnlocalizedName("rubySilverRing").setTextureName("ruby_silver_ring")));
            itemRegistry.addObject(6131, "quartz_silver_ring", (new ItemValarBase().setUnlocalizedName("quartzSilverRing").setTextureName("quartz_silver_ring")));
            itemRegistry.addObject(6132, "amber_silver_ring", (new ItemValarBase().setUnlocalizedName("amberSilverRing").setTextureName("amber_silver_ring")));
            itemRegistry.addObject(6133, "bronze_ring", (new ItemValarBase().setUnlocalizedName("bronzeRing").setTextureName("bronze_ring")));
            itemRegistry.addObject(6134, "onyx_bronze_ring", (new ItemValarBase().setUnlocalizedName("onyxBronzeRing").setTextureName("onyx_bronze_ring")));
            itemRegistry.addObject(6135, "tanzanite_bronze_ring", (new ItemValarBase().setUnlocalizedName("tanzaniteBronzeRing").setTextureName("tanzanite_bronze_ring")));
            itemRegistry.addObject(6136, "jade_bronze_ring", (new ItemValarBase().setUnlocalizedName("jadeBronzeRing").setTextureName("jade_bronze_ring")));
            itemRegistry.addObject(6137, "moonstone_bronze_ring", (new ItemValarBase().setUnlocalizedName("moonstoneBronzeRing").setTextureName("moonstone_bronze_ring")));
            itemRegistry.addObject(6138, "amethyst_bronze_ring", (new ItemValarBase().setUnlocalizedName("amethystBronzeRing").setTextureName("amethyst_bronze_ring")));
            itemRegistry.addObject(6139, "ruby_bronze_ring", (new ItemValarBase().setUnlocalizedName("rubyBronzeRing").setTextureName("ruby_bronze_ring")));
            itemRegistry.addObject(6140, "quartz_bronze_ring", (new ItemValarBase().setUnlocalizedName("quartzBronzeRing").setTextureName("quartz_bronze_ring")));
            itemRegistry.addObject(6141, "amber_bronze_ring", (new ItemValarBase().setUnlocalizedName("amberBronzeRing").setTextureName("amber_bronze_ring")));
            itemRegistry.addObject(6142, "mithril_ring", (new ItemValarBase().setUnlocalizedName("mithrilRing").setTextureName("mithril_ring")));
            itemRegistry.addObject(6143, "onyx_mithril_ring", (new ItemValarBase().setUnlocalizedName("onyxMithrilRing").setTextureName("onyx_mithril_ring")));
            itemRegistry.addObject(6144, "tanzanite_mithril_ring", (new ItemValarBase().setUnlocalizedName("tanzaniteMithrilRing").setTextureName("tanzanite_mithril_ring")));
            itemRegistry.addObject(6145, "jade_mithril_ring", (new ItemValarBase().setUnlocalizedName("jadeMithrilRing").setTextureName("jade_mithril_ring")));
            itemRegistry.addObject(6146, "moonstone_mithril_ring", (new ItemValarBase().setUnlocalizedName("moonstoneMithrilRing").setTextureName("moonstone_mithril_ring")));
            itemRegistry.addObject(6147, "amethyst_mithril_ring", (new ItemValarBase().setUnlocalizedName("amethystMithrilRing").setTextureName("amethyst_mithril_ring")));
            itemRegistry.addObject(6148, "ruby_mithril_ring", (new ItemValarBase().setUnlocalizedName("rubyMithrilRing").setTextureName("ruby_mithril_ring")));
            itemRegistry.addObject(6149, "quartz_mithril_ring", (new ItemValarBase().setUnlocalizedName("quartzMithrilRing").setTextureName("quartz_mithril_ring")));
            itemRegistry.addObject(6150, "amber_mithril_ring", (new ItemValarBase().setUnlocalizedName("amberMithrilRing").setTextureName("amber_mithril_ring")));
            itemRegistry.addObject(6151, "salt", (new ItemValarBase().setUnlocalizedName("salt").setTextureName("salt")));
            itemRegistry.addObject(6152, "noldor_chestplate", (new ItemValarBase().setUnlocalizedName("noldorChestplate").setTextureName("noldor_chestplate")));
            itemRegistry.addObject(6153, "silver_ingot", (new ItemValarBase().setUnlocalizedName("silverIngot").setTextureName("silver_ingot")));
            itemRegistry.addObject(6154, "dwarf_door_item", (new ItemValarDoor((BlockValarDoor)Blocks.dwarfDoor).setUnlocalizedName("dwarfDoorItem").setTextureName("dwarf_door_item")));
            itemRegistry.addObject(6155, "boromirs_sword", (new ItemValarWeapon(900, 9, 0, true, false).setUnlocalizedName("boromirsSword").setTextureName("boromirs_sword")));
            //itemRegistry.addObject(6156, "grey_potion", (new ItemValarBase().setUnlocalizedName("greyPotion").setTextureName("grey_potion")));
            //itemRegistry.addObject(6157, "blue_potion", (new ItemValarBase().setUnlocalizedName("bluePotion").setTextureName("blue_potion")));
            //itemRegistry.addObject(6158, "brown_potion", (new ItemValarBase().setUnlocalizedName("brownPotion").setTextureName("brown_potion")));
            //itemRegistry.addObject(6159, "dark_green_potion", (new ItemValarBase().setUnlocalizedName("darkGreenPotion").setTextureName("dark_green_potion")));
            //itemRegistry.addObject(6160, "elanor_potion", (new ItemValarBase().setUnlocalizedName("elanorPotion").setTextureName("elanor_potion")));
            //itemRegistry.addObject(6161, "light_purple_potion", (new ItemValarBase().setUnlocalizedName("lightPurplePotion").setTextureName("light_purple_potion")));
            //itemRegistry.addObject(6162, "orc_potion", (new ItemValarBase().setUnlocalizedName("orcPotion").setTextureName("orc_potion")));
            itemRegistry.addObject(6163, "orc_sword_1", (new ItemValarWeapon(230, 5, 0, true, true).setUnlocalizedName("orcSword1").setTextureName("orc_sword_1")));
            itemRegistry.addObject(6164, "orc_sword_2", (new ItemValarWeapon(230, 5).setUnlocalizedName("orcSword2").setTextureName("orc_sword_2")));
            //itemRegistry.addObject(6165, "rivendell_sword", (new ItemValarBase().setUnlocalizedName("rivendellSword").setTextureName("rivendell_sword")));
            itemRegistry.addObject(6166, "goblin_sword", (new ItemValarWeapon(200, 5).setUnlocalizedName("goblinSword").setTextureName("goblin_sword")));
            itemRegistry.addObject(6167, "hobbit_axe", (new ItemValarWeapon(235, 5, 0, true, true).setUnlocalizedName("hobbitAxe").setTextureName("hobbit_axe")));
            itemRegistry.addObject(6168, "sharkus_shortsword", (new ItemValarWeapon(467, 8).setUnlocalizedName("sharkusShortsword").setTextureName("sharkus_shortsword")));
            itemRegistry.addObject(6169, "battle_pickaxe", (new ItemValarWeapon(300, 5).setUnlocalizedName("battlePickaxe").setTextureName("battle_pickaxe")));
            itemRegistry.addObject(6170, "shirriff_club", (new ItemValarWeapon(131, 6).setUnlocalizedName("shirriffClub").setTextureName("shirriff_club")));
            itemRegistry.addObject(6171, "pike_club", (new ItemValarWeapon(350, 6).setUnlocalizedName("pikeClub").setTextureName("pike_club")));
            itemRegistry.addObject(6172, "hobbit_sword", (new ItemValarWeapon(230, 5).setUnlocalizedName("hobbitSword").setTextureName("hobbit_sword")));
            itemRegistry.addObject(6173, "hobbit_hammer", (new ItemValarWeapon(235, 5).setUnlocalizedName("hobbitHammer").setTextureName("hobbit_hammer")));
            //itemRegistry.addObject(6174, "dwarven_axe_moria", (new ItemValarBase().setUnlocalizedName("dwarvenAxeMoria").setTextureName("dwarvenaxemoria")));
            itemRegistry.addObject(6175, "green_arrow", (new ItemValarBase().setUnlocalizedName("greenArrow").setTextureName("green_arrow")));
            itemRegistry.addObject(6176, "black_arrow", (new ItemValarBase().setUnlocalizedName("blackArrow").setTextureName("black_arrow")));
            itemRegistry.addObject(6177, "goblin_arrow", (new ItemValarBase().setUnlocalizedName("goblinArrow").setTextureName("goblin_arrow")));
            itemRegistry.addObject(6179, "red_arrow", (new ItemValarBase().setUnlocalizedName("redArrow").setTextureName("red_arrow")));
            itemRegistry.addObject(6179, "yellow_arrow", (new ItemValarBase().setUnlocalizedName("yellowArrow").setTextureName("yellow_arrow")));
            //itemRegistry.addObject(6180, "throwing_rock", (new ItemValarBase().setUnlocalizedName("throwingRock").setTextureName("throwing_rock")));
            itemRegistry.addObject(6181, "boar_horns", (new ItemValarBase().setUnlocalizedName("boarHorns").setTextureName("boar_horns")));
            itemRegistry.addObject(6182, "gold_ring_of_darkness", (new ItemValarBase().setUnlocalizedName("goldRingofDarkness").setTextureName("gold_ring_of_darkness")));
            itemRegistry.addObject(6183, "gold_ring_of_earth", (new ItemValarBase().setUnlocalizedName("goldRingofEarth").setTextureName("gold_ring_of_earth")));
            itemRegistry.addObject(6184, "gold_ring_of_fire", (new ItemValarBase().setUnlocalizedName("goldRingofFire").setTextureName("gold_ring_of_fire")));
            itemRegistry.addObject(6185, "gold_ring_of_greed", (new ItemValarBase().setUnlocalizedName("goldRingofGreed").setTextureName("gold_ring_of_greed")));
            itemRegistry.addObject(6186, "gold_ring_of_hope", (new ItemValarBase().setUnlocalizedName("goldRingofHope").setTextureName("gold_ring_of_hope")));
            itemRegistry.addObject(6187, "gold_ring_of_nature", (new ItemValarBase().setUnlocalizedName("goldRingofNature").setTextureName("gold_ring_of_nature")));
            itemRegistry.addObject(6188, "gold_ring_of_sea", (new ItemValarBase().setUnlocalizedName("goldRingofSea").setTextureName("gold_ring_of_sea")));
            itemRegistry.addObject(6189, "gold_ring_of_sky", (new ItemValarBase().setUnlocalizedName("goldRingofSky").setTextureName("gold_ring_of_sky")));
            itemRegistry.addObject(6190, "gold_ring_of_sunlight", (new ItemValarBase().setUnlocalizedName("goldRingofSunlight").setTextureName("gold_ring_of_sunlight")));
            itemRegistry.addObject(6191, "gold_ring_of_wealth", (new ItemValarBase().setUnlocalizedName("goldRingofWealth").setTextureName("gold_ring_of_wealth")));
            itemRegistry.addObject(6192, "gold_ring_of_wind", (new ItemValarBase().setUnlocalizedName("goldRingofWind").setTextureName("gold_ring_of_wind")));
            itemRegistry.addObject(6193, "silver_ring_of_darkness", (new ItemValarBase().setUnlocalizedName("silverRingofDarkness").setTextureName("silver_ring_of_darkness")));
            itemRegistry.addObject(6194, "silver_ring_of_earth", (new ItemValarBase().setUnlocalizedName("silverRingofEarth").setTextureName("silver_ring_of_earth")));
            itemRegistry.addObject(6195, "silver_ring_of_fire", (new ItemValarBase().setUnlocalizedName("silverRingofFire").setTextureName("silver_ring_of_fire")));
            itemRegistry.addObject(6196, "silver_ring_of_greed", (new ItemValarBase().setUnlocalizedName("silverRingofGreed").setTextureName("silver_ring_of_greed")));
            itemRegistry.addObject(6197, "silver_ring_of_hope", (new ItemValarBase().setUnlocalizedName("silverRingofHope").setTextureName("silver_ring_of_hope")));
            itemRegistry.addObject(6198, "silver_ring_of_nature", (new ItemValarBase().setUnlocalizedName("silverRingofNature").setTextureName("silver_ring_of_nature")));
            itemRegistry.addObject(6199, "silver_ring_of_sea", (new ItemValarBase().setUnlocalizedName("silverRingofSea").setTextureName("silver_ring_of_sea")));
            itemRegistry.addObject(6200, "silver_ring_of_sky", (new ItemValarBase().setUnlocalizedName("silverRingofSky").setTextureName("silver_ring_of_sky")));
            itemRegistry.addObject(6201, "silver_ring_of_sunlight", (new ItemValarBase().setUnlocalizedName("silverRingofSunlight").setTextureName("silver_ring_of_sunlight")));
            itemRegistry.addObject(6202, "silver_ring_of_wealth", (new ItemValarBase().setUnlocalizedName("silverRingofWealth").setTextureName("silver_ring_of_wealth")));
            itemRegistry.addObject(6203, "silver_ring_of_wind", (new ItemValarBase().setUnlocalizedName("silverRingofWind").setTextureName("silver_ring_of_wind")));
            itemRegistry.addObject(6204, "bronze_ring_of_darkness", (new ItemValarBase().setUnlocalizedName("bronzeRingofDarkness").setTextureName("bronze_ring_of_darkness")));
            itemRegistry.addObject(6205, "bronze_ring_of_earth", (new ItemValarBase().setUnlocalizedName("bronzeRingofEarth").setTextureName("bronze_ring_of_earth")));
            itemRegistry.addObject(6206, "bronze_ring_of_fire", (new ItemValarBase().setUnlocalizedName("bronzeRingofFire").setTextureName("bronze_ring_of_fire")));
            itemRegistry.addObject(6207, "bronze_ring_of_greed", (new ItemValarBase().setUnlocalizedName("bronzeRingofGreed").setTextureName("bronze_ring_of_greed")));
            itemRegistry.addObject(6208, "bronze_ring_of_hope", (new ItemValarBase().setUnlocalizedName("bronzeRingofHope").setTextureName("bronze_ring_of_hope")));
            itemRegistry.addObject(6209, "bronze_ring_of_nature", (new ItemValarBase().setUnlocalizedName("bronzeRingofNature").setTextureName("bronze_ring_of_nature")));
            itemRegistry.addObject(6210, "bronze_ring_of_sea", (new ItemValarBase().setUnlocalizedName("bronzeRingofSea").setTextureName("bronze_ring_of_sea")));
            itemRegistry.addObject(6211, "bronze_ring_of_sky", (new ItemValarBase().setUnlocalizedName("bronzeRingofSky").setTextureName("bronze_ring_of_sky")));
            itemRegistry.addObject(6212, "bronze_ring_of_sunlight", (new ItemValarBase().setUnlocalizedName("bronzeRingofSunlight").setTextureName("bronze_ring_of_sunlight")));
            itemRegistry.addObject(6213, "bronze_ring_of_wealth", (new ItemValarBase().setUnlocalizedName("bronzeRingofWealth").setTextureName("bronze_ring_of_wealth")));
            itemRegistry.addObject(6214, "bronze_ring_of_wind", (new ItemValarBase().setUnlocalizedName("bronzeRingofWind").setTextureName("bronze_ring_of_wind")));
            itemRegistry.addObject(6215, "mithril_ring_of_darkness", (new ItemValarBase().setUnlocalizedName("mithrilRingofDarkness").setTextureName("mithril_ring_of_darkness")));
            itemRegistry.addObject(6216, "mithril_ring_of_earth", (new ItemValarBase().setUnlocalizedName("mithrilRingofEarth").setTextureName("mithril_ring_of_earth")));
            itemRegistry.addObject(6217, "mithril_ring_of_fire", (new ItemValarBase().setUnlocalizedName("mithrilRingofFire").setTextureName("mithril_ring_of_fire")));
            itemRegistry.addObject(6218, "mithril_ring_of_greed", (new ItemValarBase().setUnlocalizedName("mithrilRingofGreed").setTextureName("mithril_ring_of_greed")));
            itemRegistry.addObject(6219, "mithril_ring_of_hope", (new ItemValarBase().setUnlocalizedName("mithrilRingofHope").setTextureName("mithril_ring_of_hope")));
            itemRegistry.addObject(6220, "mithril_ring_of_nature", (new ItemValarBase().setUnlocalizedName("mithrilRingofNature").setTextureName("mithril_ring_of_nature")));
            itemRegistry.addObject(6221, "mithril_ring_of_sea", (new ItemValarBase().setUnlocalizedName("mithrilRingofSea").setTextureName("mithril_ring_of_sea")));
            itemRegistry.addObject(6222, "mithril_ring_of_sky", (new ItemValarBase().setUnlocalizedName("mithrilRingofSky").setTextureName("mithril_ring_of_sky")));
            itemRegistry.addObject(6223, "mithril_ring_of_sunlight", (new ItemValarBase().setUnlocalizedName("mithrilRingofSunlight").setTextureName("mithril_ring_of_sunlight")));
            itemRegistry.addObject(6224, "mithril_ring_of_wealth", (new ItemValarBase().setUnlocalizedName("mithrilRingofWealth").setTextureName("mithril_ring_of_wealth")));
            itemRegistry.addObject(6225, "mithril_ring_of_wind", (new ItemValarBase().setUnlocalizedName("mithrilRingofWind").setTextureName("mithril_ring_of_wind")));
            itemRegistry.addObject(6226, "anduril", (new ItemValarWeapon(3000, 11, 0, true, false).setUnlocalizedName("anduril").setTextureName("anduril")));
            itemRegistry.addObject(6227, "morgul_sword", (new ItemValarWeapon(2500, 9).setUnlocalizedName("morgulSword").setTextureName("morgul_sword")));
            itemRegistry.addObject(6228, "elven_long_sword", (new ItemValarWeapon(1800, 7).setUnlocalizedName("elvenLongSword").setTextureName("elven_long_sword")));
            itemRegistry.addObject(6229, "berserker_sword", (new ItemValarWeapon(1400, 8).setUnlocalizedName("berserkerSword").setTextureName("berserker_sword")));
            itemRegistry.addObject(6230, "two_handed_sword", (new ItemValarWeapon(500, 7).setUnlocalizedName("twohandedSword").setTextureName("two_handed_sword")));
            //itemRegistry.addObject(6231, "green_flag", (new ItemValarBase().setUnlocalizedName("greenFlag").setTextureName("green_flag")));
            //itemRegistry.addObject(6232, "hobbit_bow", (new ItemValarBase().setUnlocalizedName("hobbitBow").setTextureName("hobbit_bow")));
            itemRegistry.addObject(6233, "rohan_sheild_6", (new ItemValarBase().setUnlocalizedName("rohanShield6").setTextureName("rohan_shield_6")));
            //itemRegistry.addObject(6234, "throwing_stone", (new ItemValarBase().setUnlocalizedName("throwingStone").setTextureName("throwing_stone")));
            itemRegistry.addObject(6235, "rohirrim_axe", (new ItemValarWeapon(267, 6, 0, true, true).setUnlocalizedName("rohirrimAxe").setTextureName("rohirrim_axe")));
            itemRegistry.addObject(6236, "ecthelions_boots", (new ItemValarArmor(3, 500, 3, 0).setUnlocalizedName("ecthelionsBoots").setTextureName("ecthelions_boots")));
            //itemRegistry.addObject(3237, "gondorian_brick_stone_slab_item", (new ItemValarBase().setUnlocalizedName("gondorianBrickStoneSlabItem").setTextureName("gondorian_brick_stone_slab_item")));
            //itemRegistry.addObject(6238, "a_knife_in_the_dark", (new ItemValarBase().setUnlocalizedName("aKnifeintheDark").setTextureName("a_knife_in_the_dark")));*/
            ELVEN_DOOR = getRegisteredItem("elven_door");
            HUMAN_DOOR = getRegisteredItem("human_door");
            /*itemRegistry.addObject(6241, "green_bed_item", (new ItemValarBed((BlockValarBed)Blocks.greenBed).setUnlocalizedName("greenBedItem").setTextureName("green_bed_item")));
            //itemRegistry.addObject(6242, "one_ring", (new ItemValarBase().setUnlocalizedName("oneRing").setTextureName("one_ring")));
            itemRegistry.addObject(6243, "aicanar", (new ItemValarWeapon(6000, 10).setUnlocalizedName("aicanar").setTextureName("aicanar")));
            itemRegistry.addObject(6244, "balins_sword", (new ItemValarWeapon(1600, 7).setUnlocalizedName("balinsSword").setTextureName("balins_sword")));
            itemRegistry.addObject(6245, "bifurs_spear", (new ItemValarWeapon(1102, 6, 0, true, true).setUnlocalizedName("bifursSpear").setTextureName("bifurs_spear")));
            //itemRegistry.addObject(6246, "bofurs_spear", (new ItemValarWeapon(1182, 6).setUnlocalizedName("bofursSpear").setTextureName("bofurs_spear")));
            itemRegistry.addObject(6247, "bomburs_spoon", (new ItemValarWeapon(321, 4).setUnlocalizedName("bombursSpoon").setTextureName("bomburs_spoon")));
            itemRegistry.addObject(6248, "doris_sword", (new ItemValarWeapon(1500, 5).setUnlocalizedName("dorisSword").setTextureName("doris_sword")));
            itemRegistry.addObject(6249, "dwalins_axe", (new ItemValarWeapon(1700, 7).setUnlocalizedName("dwalinsAxe").setTextureName("dwalins_axe")));
            itemRegistry.addObject(6250, "filis_knife", (new ItemValarWeapon(112, 4).setUnlocalizedName("filisKnife").setTextureName("filis_knife")));
            itemRegistry.addObject(6251, "filis_sword", (new ItemValarWeapon(1111, 6).setUnlocalizedName("filisSword").setTextureName("filis_sword")));
            itemRegistry.addObject(6252, "kilis_sword", (new ItemValarWeapon(1111, 6).setUnlocalizedName("kilisSword").setTextureName("kilis_sword")));
            itemRegistry.addObject(6253, "noris_club", (new ItemValarWeapon(861, 5).setUnlocalizedName("norisClub").setTextureName("noris_club")));
            itemRegistry.addObject(6254, "oins_staff", (new ItemValarWeapon(922, 6).setUnlocalizedName("oinsStaff").setTextureName("oins_staff")));
            itemRegistry.addObject(6255, "orcrist", (new ItemValarWeapon(8001, 12).setUnlocalizedName("orcrist").setTextureName("orcrist")));
            itemRegistry.addObject(6256, "sword_of_westernesse", (new ItemValarWeapon(3200, 8).setUnlocalizedName("swordOfWesternesse").setTextureName("sword_of_westernesse")));
            itemRegistry.addObject(6257, "thorins_sword", (new ItemValarWeapon(1200, 6).setUnlocalizedName("thorinsSword").setTextureName("thorins_sword")));
            itemRegistry.addObject(6258, "thrains_warhammer", (new ItemValarWeapon(1288, 6).setUnlocalizedName("thrainsWarhammer").setTextureName("thrains_warhammer")));
            itemRegistry.addObject(6259, "thrors_warhammer", (new ItemValarWeapon(1428, 7).setUnlocalizedName("throrsWarhammer").setTextureName("thrors_warhammer")));
            itemRegistry.addObject(6260, "aragorns_elf_knife", (new ItemValarWeapon(1300, 5, 0, true, true).setUnlocalizedName("aragornsElfKnife").setTextureName("aragorns_elf_knife")));
            itemRegistry.addObject(6261, "eowyns_sword", (new ItemValarWeapon(1261, 6).setUnlocalizedName("eowynsSword").setTextureName("eowyns_sword")));
            itemRegistry.addObject(6262, "gandalf_the_greys_staff", (new ItemValarWeapon(3000, 9).setUnlocalizedName("gandalftheGreysStaff").setTextureName("gandalf_the_greys_staff")));
            itemRegistry.addObject(6263, "gandalf_the_whites_staff", (new ItemValarWeapon(5000, 11).setUnlocalizedName("gandalftheWhitesStaff").setTextureName("gandalf_the_whites_staff")));
            itemRegistry.addObject(6264, "gimlis_two-headed_axe", (new ItemValarWeapon(2000, 9).setUnlocalizedName("gimlisTwo-HeadedAxe").setTextureName("gimlis_two-headed_axe")));
            itemRegistry.addObject(6265, "gimlis_longaxe", (new ItemValarWeapon(1700, 7).setUnlocalizedName("gimlisLongaxe").setTextureName("gimlis_longaxe")));
            itemRegistry.addObject(6266, "glamdring", (new ItemValarWeapon(3200, 11).setUnlocalizedName("glamdring").setTextureName("glamdring")));
            itemRegistry.addObject(6267, "gloins_axe", (new ItemValarWeapon(1700, 7).setUnlocalizedName("gloinsAxe").setTextureName("gloins_axe")));
            itemRegistry.addObject(6268, "glorfindels_sword", (new ItemValarWeapon(3600, 9).setUnlocalizedName("glorfindelsSword").setTextureName("glorfindels_sword")));
            itemRegistry.addObject(6269, "guthwine", (new ItemValarWeapon(1732, 8).setUnlocalizedName("guthwine").setTextureName("guthwine")));
            itemRegistry.addObject(6270, "hadhafang", (new ItemValarWeapon(3400, 10).setUnlocalizedName("hadhafang").setTextureName("hadhafang")));
            //itemRegistry.addObject(6271, "herugrim", (new ItemValarBase().setUnlocalizedName("herugrim").setTextureName("herugrim")));
            itemRegistry.addObject(6272, "legolas_sword", (new ItemValarWeapon(2900, 9, 0, true, true).setUnlocalizedName("legolasSword").setTextureName("legolas_sword")));
            itemRegistry.addObject(6273, "radagasts_staff", (new ItemValarWeapon(3100, 8, 0, true, true).setUnlocalizedName("radagast'sStaff").setTextureName("radagasts_staff")));
            itemRegistry.addObject(6274, "lurtz_sword", (new ItemValarWeapon(1870, 8).setUnlocalizedName("lurtzSword").setTextureName("lurtz_sword")));
            itemRegistry.addObject(6275, "saurons_mace", (new ItemValarWeapon(7500, 13).setUnlocalizedName("sauronsMace").setTextureName("saurons_mace")));
            itemRegistry.addObject(6276, "sarumans_staff", (new ItemValarWeapon(4500, 10).setUnlocalizedName("sarumansStaff").setTextureName("sarumans_staff")));
            itemRegistry.addObject(6277, "yaznegs_axe", (new ItemValarWeapon(830, 6, 0, true, true).setUnlocalizedName("yaznegsAxe").setTextureName("yaznegs_axe")));
            itemRegistry.addObject(6278, "dwarven_lord_knife", (new ItemValarWeapon(1200, 4).setUnlocalizedName("dwarvenLordKnife").setTextureName("dwarven_lord_knife")));
            itemRegistry.addObject(6279, "gondorian_noble_sword", (new ItemValarWeapon(1400, 7).setUnlocalizedName("gondorianNobleSword").setTextureName("gondorian_noble_sword")));
            itemRegistry.addObject(6280, "mace_of_glory", (new ItemValarWeapon(2100, 8).setUnlocalizedName("maceOfGlory").setTextureName("mace_of_glory")));
            itemRegistry.addObject(6281, "golden_war_hammer_of_erebor", (new ItemValarWeapon(2800, 7).setUnlocalizedName("goldenWarHammerofErebor").setTextureName("golden_war_hammer_of_erebor")));
            itemRegistry.addObject(6282, "gondorian_spear", (new ItemValarWeapon(1000, 6).setUnlocalizedName("gondorianSpear").setTextureName("gondorian_spear")));
            itemRegistry.addObject(6283, "rohirrim_spear", (new ItemValarWeapon(1040, 6).setUnlocalizedName("rohirrimSpear").setTextureName("rohirrim_spear")));
            itemRegistry.addObject(6284, "bull-head_mace", (new ItemValarWeapon(1091, 6).setUnlocalizedName("bull-HeadMace").setTextureName("bull-head_mace")));
            itemRegistry.addObject(6285, "corsair_eket", (new ItemValarWeapon(1133, 7).setUnlocalizedName("corsairEket").setTextureName("corsair_eket")));
            itemRegistry.addObject(6286, "dol_guldur_spiked_mace", (new ItemValarWeapon(981, 6).setUnlocalizedName("dolGuldurSpikedMace").setTextureName("dol_guldur_spiked_mace")));
            itemRegistry.addObject(6287, "fell-wargrider_sword", (new ItemValarWeapon(991, 6, 0, true, true).setUnlocalizedName("fell-WargriderSword").setTextureName("fell-wargrider_sword")));
            itemRegistry.addObject(6288, "haradrim_snake_dagger", (new ItemValarWeapon(777, 5).setUnlocalizedName("haradrimSnakeDagger").setTextureName("haradrim_snake_dagger")));
            itemRegistry.addObject(6289, "north-goblin_mace", (new ItemValarWeapon(531, 5).setUnlocalizedName("north-GoblinMace").setTextureName("north-goblin_mace")));
            itemRegistry.addObject(6290, "north-goblin_sword", (new ItemValarWeapon(772, 5).setUnlocalizedName("north-GoblinSword").setTextureName("north-goblin_sword")));
            itemRegistry.addObject(6291, "orc_captain_sword", (new ItemValarWeapon(1130, 7).setUnlocalizedName("orcCaptainSword").setTextureName("orc_captain_sword")));
            itemRegistry.addObject(6292, "orc_dagger", (new ItemValarWeapon(103, 4).setUnlocalizedName("orcDagger").setTextureName("orc_dagger")));
            itemRegistry.addObject(6293, "orc_halbard", (new ItemValarWeapon(605, 7, 0, true, true).setUnlocalizedName("orcHalbard").setTextureName("orc_halbard")));
            itemRegistry.addObject(6294, "uruk_siege-trooper_dagger", (new ItemValarWeapon(1041, 5).setUnlocalizedName("urukSiege-TrooperDagger").setTextureName("uruk_siege-trooper_dagger")));
            //itemRegistry.addObject(6295, "orc_spawner", (new ItemValarBase().setUnlocalizedName("orcSpawner").setTextureName("orc_spawner")));
            itemRegistry.addObject(6296, "iron_mace", (new ItemValarWeapon(387, 7).setUnlocalizedName("ironMace").setTextureName("iron_mace")));
            itemRegistry.addObject(6297, "orc_sword_3", (new ItemValarWeapon(837, 6).setUnlocalizedName("orcSword3").setTextureName("orc_sword_3")));
            itemRegistry.addObject(6298, "morannon_orc_shield", (new ItemValarBase().setUnlocalizedName("morannonOrcShield").setTextureName("morannon_orc_shield")));
            itemRegistry.addObject(6299, "morannon_dagger", (new ItemValarWeapon(99, 3).setUnlocalizedName("morannonDagger").setTextureName("morannon_dagger")));
            itemRegistry.addObject(6300, "orc_spear", (new ItemValarWeapon(123, 6).setUnlocalizedName("orcSpear").setTextureName("orc_spear")));
            itemRegistry.addObject(6301, "net", (new ItemValarBase().setUnlocalizedName("net").setTextureName("net")));
            //itemRegistry.addObject(6302, "erus_staff", (new ItemValarErusStaff()).setUnlocalizedName("erusStaff").setTextureName("erus_staff"));*/
            CASTLE_DOOR = getRegisteredItem("castle_door");
            DOL_GULDUR_PRISON_DOOR = getRegisteredItem("dol_guldur_prison_door");
            HILLMEN_DOOR = getRegisteredItem("hillmen_door");
            MORDOR_DOOR = getRegisteredItem("mordor_door");
            PRISON_DOOR = getRegisteredItem("prison_door");
            SINDAR_DOOR = getRegisteredItem("sindar_door");
            /*itemRegistry.addObject(6309, "southlinch_seed", (new ItemValarCrops((BlockValarCrops)Blocks.southlinch)).setUnlocalizedName("southlinchSeed").setTextureName("southlinch_seed"));
            itemRegistry.addObject(6310, "green_grape_seed", (new ItemValarCrops((BlockValarCrops)Blocks.greenGrape)).setUnlocalizedName("greenGrapeSeed").setTextureName("green_grape_seed"));
            itemRegistry.addObject(6311, "green_grapes", (new ItemValarFood(2, 0.3F, false)).setUnlocalizedName("greenGrapes").setTextureName("green_grapes"));
            itemRegistry.addObject(6312, "purple_grape_seed", (new ItemValarCrops((BlockValarCrops)Blocks.purpleGrape)).setUnlocalizedName("purpleGrapeSeed").setTextureName("purple_grape_seed"));
            itemRegistry.addObject(6313, "purple_grapes", (new ItemValarFood(2, 0.3F, false)).setUnlocalizedName("purpleGrapes").setTextureName("purple_grapes"));
            itemRegistry.addObject(6314, "pipeweed_seed", (new ItemValarCrops((BlockValarCrops)Blocks.pipeweedPlant)).setUnlocalizedName("pipeweedSeed").setTextureName("pipeweed_seed"));
            itemRegistry.addObject(6315, "pea_seed", (new ItemValarCrops((BlockValarCrops)Blocks.peaPlant)).setUnlocalizedName("peaSeed").setTextureName("pea_seed"));
            itemRegistry.addObject(6316, "peas", (new ItemValarFood(1, 0.6F, false)).setUnlocalizedName("peas").setTextureName("peas"));
            itemRegistry.addObject(6317, "leek", (new ItemValarFood(3, 0.6F, false)).setUnlocalizedName("leek").setTextureName("leek"));
            itemRegistry.addObject(6318, "leek_seed", (new ItemValarCrops((BlockValarCrops)Blocks.leekPlant)).setUnlocalizedName("leekSeed").setTextureName("leek_seed"));
            itemRegistry.addObject(6319, "onion_seed", (new ItemValarCrops((BlockValarCrops)Blocks.onionPlant)).setUnlocalizedName("onionSeed").setTextureName("onion_seed"));
            itemRegistry.addObject(6320, "onion", (new ItemValarFood(3, 0.6F, false)).setUnlocalizedName("onion").setTextureName("onion"));
            itemRegistry.addObject(6321, "old_toby_seed", (new ItemValarCrops((BlockValarCrops)Blocks.oldTobyPlant)).setUnlocalizedName("oldTobySeed").setTextureName("old_toby_seed"));
            itemRegistry.addObject(6322, "southern_star_seed", (new ItemValarCrops((BlockValarCrops)Blocks.southernStarPlant)).setUnlocalizedName("southernStarSeed").setTextureName("southern_star_seed"));
            itemRegistry.addObject(6323, "strawberry_seed", (new ItemValarCrops((BlockValarCrops)Blocks.strawberryBush)).setUnlocalizedName("strawberrySeed").setTextureName("strawberry_seed"));
            itemRegistry.addObject(6324, "azogs_mace", (new ItemValarWeapon(3500, 7, 0, true, false)).setUnlocalizedName("azogsMace").setTextureName("azogs_mace"));
            // Temporary Id, change to proper id when adding items
            //itemRegistry.addObject(10002, "rucksack", (new ItemValarRucksack()).setUnlocalizedName("rucksack").setTextureName("rucksack"));
            //itemRegistry.addObject(10003, "frodos_finger", (new ItemValarFood(2, 0.1F, true).setUnlocalizedName("frodosFinger").setTextureName("frodos_finger")));
            //itemRegistry.addObject(10004, "two_handed_sword", (new ItemValarWeapon(1, 20, 0, true).setUnlocalizedName("twoHandedSword").setTextureName("two_handed_sword")));
            //itemRegistry.addObject(10005, "easterling_helmet", (new ItemValarArmor(0, 1000, 2, 0).setUnlocalizedName("easterlingHelmet").setTextureName("easterling_helmet")));
            //itemRegistry.addObject(10006, "miruvoir", (new ItemValarDrinkable(Items.glass_bottle).setUnlocalizedName("miruvoir").setTextureName("miruvoir")));*/
            // End Awaken Dreams code
        }
    }
}
